// ============================================================
// questions-general.js — general Word knowledge questions
// 15 questions per level x 5 levels = 75 questions
// Trilingual: ar / en / fr — option order & "correct" index match across languages
// ============================================================

const GENERAL_Q = [
  /* ===================== LEVEL 1 ===================== */
  { level: 1, correct: 0,
    ar: { q: 'ما امتداد ملفات وورد الحديثة؟', options: ['.docx', '.xlsx', '.pptx', '.pdf'] },
    en: { q: 'What is the file extension of modern Word files?', options: ['.docx', '.xlsx', '.pptx', '.pdf'] },
    fr: { q: "Quelle est l'extension des fichiers Word modernes ?", options: ['.docx', '.xlsx', '.pptx', '.pdf'] } },
  { level: 1, correct: 1,
    ar: { q: 'ماذا تفعل أيقونة القرص المرن 💾 في شريط الأدوات السريع؟', options: ['طباعة المستند', 'حفظ المستند', 'نسخ النص', 'البحث في المستند'] },
    en: { q: 'What does the floppy disk icon 💾 in the Quick Access Toolbar do?', options: ['Print the document', 'Save the document', 'Copy text', 'Search the document'] },
    fr: { q: "Que fait l'icône disquette 💾 dans la barre d'outils Accès rapide ?", options: ['Imprimer le document', 'Enregistrer le document', 'Copier le texte', 'Rechercher dans le document'] } },
  { level: 1, correct: 2,
    ar: { q: 'ما وظيفة زر "تراجع" (Undo)؟', options: ['حفظ الملف', 'إغلاق البرنامج', 'التراجع عن آخر إجراء', 'تكبير الخط'] },
    en: { q: 'What does the "Undo" button do?', options: ['Save the file', 'Close the program', 'Undo the last action', 'Increase font size'] },
    fr: { q: 'Que fait le bouton « Annuler » ?', options: ['Enregistrer le fichier', 'Fermer le programme', 'Annuler la dernière action', 'Augmenter la taille de police'] } },
  { level: 1, correct: 0,
    ar: { q: 'أين تجد أدوات تغيير لون ونوع الخط عادةً؟', options: ['تبويب الصفحة الرئيسية', 'تبويب الإدراج', 'تبويب المراجعة', 'تبويب العرض'] },
    en: { q: 'Where do you usually find tools to change font color and type?', options: ['The Home tab', 'The Insert tab', 'The Review tab', 'The View tab'] },
    fr: { q: "Où trouve-t-on généralement les outils pour changer la couleur et le type de police ?", options: ["L'onglet Accueil", "L'onglet Insertion", "L'onglet Révision", "L'onglet Affichage"] } },
  { level: 1, correct: 0,
    ar: { q: 'ما وظيفة زر "توسيط" في التنسيق؟', options: ['توسيط الفقرة بين الهامشين', 'زيادة حجم الخط', 'حذف التنسيق', 'إدراج جدول'] },
    en: { q: 'What does the "Center" formatting button do?', options: ['Center the paragraph between the margins', 'Increase font size', 'Remove formatting', 'Insert a table'] },
    fr: { q: 'Que fait le bouton de mise en forme « Centrer » ?', options: ['Centrer le paragraphe entre les marges', 'Augmenter la taille de police', 'Supprimer la mise en forme', 'Insérer un tableau'] } },
  { level: 1, correct: 1,
    ar: { q: 'كيف تبدأ فقرة جديدة أثناء الكتابة؟', options: ['بالضغط على Tab', 'بالضغط على Enter', 'بالضغط على Space', 'بالضغط على Shift'] },
    en: { q: 'How do you start a new paragraph while typing?', options: ['Press Tab', 'Press Enter', 'Press Space', 'Press Shift'] },
    fr: { q: 'Comment commencer un nouveau paragraphe en tapant ?', options: ['Appuyer sur Tab', 'Appuyer sur Entrée', 'Appuyer sur Espace', 'Appuyer sur Maj'] } },
  { level: 1, correct: 2,
    ar: { q: 'ما اسم الأداة التي تشير للأخطاء الإملائية أثناء الكتابة؟', options: ['المعاينة قبل الطباعة', 'تتبع التغييرات', 'التدقيق الإملائي', 'جدول المحتويات'] },
    en: { q: 'What is the tool that flags spelling mistakes as you type?', options: ['Print Preview', 'Track Changes', 'Spell Check', 'Table of Contents'] },
    fr: { q: "Quel est l'outil qui signale les fautes d'orthographe pendant la frappe ?", options: ["Aperçu avant impression", 'Suivi des modifications', 'Vérification orthographique', 'Table des matières'] } },
  { level: 1, correct: 0,
    ar: { q: 'أين تجد خيار "طباعة" المستند غالبًا؟', options: ['قائمة ملف (File)', 'تبويب الإدراج', 'تبويب التصميم', 'تبويب المراجعة'] },
    en: { q: 'Where is the "Print" option usually found?', options: ['The File menu', 'The Insert tab', 'The Design tab', 'The Review tab'] },
    fr: { q: "Où se trouve généralement l'option « Imprimer » ?", options: ['Le menu Fichier', "L'onglet Insertion", "L'onglet Création", "L'onglet Révision"] } },
  { level: 1, correct: 1,
    ar: { q: 'ما وظيفة "المسطرة" (Ruler) أعلى صفحة المستند؟', options: ['تغيير لون الصفحة', 'ضبط الهوامش والمسافات البادئة', 'إدراج صورة', 'التدقيق الإملائي'] },
    en: { q: 'What does the "Ruler" at the top of the document do?', options: ['Change the page color', 'Adjust margins and indents', 'Insert an image', 'Check spelling'] },
    fr: { q: 'Que fait la « Règle » en haut du document ?', options: ['Changer la couleur de la page', 'Ajuster les marges et les retraits', 'Insérer une image', "Vérifier l'orthographe"] } },
  { level: 1, correct: 1,
    ar: { q: 'كيف تحدد كلمة كاملة بسرعة بالفأرة؟', options: ['نقرة واحدة عليها', 'نقرتين متتاليتين عليها', 'نقرة ثلاثية', 'السحب فقط'] },
    en: { q: 'How do you quickly select a whole word with the mouse?', options: ['Single click on it', 'Double-click on it', 'Triple click', 'Dragging only'] },
    fr: { q: 'Comment sélectionner rapidement un mot entier avec la souris ?', options: ['Un simple clic dessus', 'Double-cliquer dessus', 'Un triple clic', 'Glisser uniquement'] } },
  { level: 1, correct: 1,
    ar: { q: 'ما اسم العلامة الوامضة التي تشير لموضع الكتابة؟', options: ['المسطرة', 'نقطة الإدراج', 'الهامش', 'الفاصل'] },
    en: { q: 'What is the blinking mark that shows the typing position called?', options: ['The ruler', 'The insertion point', 'The margin', 'The break'] },
    fr: { q: "Comment appelle-t-on le trait clignotant qui indique la position de frappe ?", options: ['La règle', "Le point d'insertion", 'La marge', 'Le saut'] } },
  { level: 1, correct: 0,
    ar: { q: 'أي تبويب يحتوي عادة على أدوات إدراج الصور والجداول؟', options: ['إدراج', 'الصفحة الرئيسية', 'المراجعة', 'العرض'] },
    en: { q: 'Which tab usually has the tools to insert images and tables?', options: ['Insert', 'Home', 'Review', 'View'] },
    fr: { q: 'Quel onglet contient généralement les outils pour insérer images et tableaux ?', options: ['Insertion', 'Accueil', 'Révision', 'Affichage'] } },
  { level: 1, correct: 1,
    ar: { q: 'ما الفرق بين "حفظ" و"حفظ باسم"؟', options: ['لا فرق بينهما', 'حفظ باسم ينشئ نسخة جديدة باسم أو مكان مختلف', 'حفظ باسم للطباعة فقط', 'حفظ يحذف الملف القديم'] },
    en: { q: 'What is the difference between "Save" and "Save As"?', options: ['No difference at all', '"Save As" creates a new copy with a different name or location', '"Save As" is only for printing', '"Save" deletes the old file'] },
    fr: { q: 'Quelle est la différence entre « Enregistrer » et « Enregistrer sous » ?', options: ['Aucune différence', '« Enregistrer sous » crée une nouvelle copie avec un nom ou un emplacement différent', '« Enregistrer sous » sert uniquement à imprimer', "« Enregistrer » supprime l'ancien fichier"] } },
  { level: 1, correct: 2,
    ar: { q: 'ما وظيفة زر "غامق" (Bold)؟', options: ['تصغير الخط', 'تلوين النص', 'جعل النص أكثر سماكة ووضوحًا', 'محاذاة النص'] },
    en: { q: 'What does the "Bold" button do?', options: ['Shrink the font', 'Color the text', 'Make the text thicker and bolder', 'Align the text'] },
    fr: { q: 'Que fait le bouton « Gras » ?', options: ['Réduire la police', 'Colorer le texte', 'Rendre le texte plus épais et plus visible', 'Aligner le texte'] } },
  { level: 1, correct: 2,
    ar: { q: 'كيف تحدد كل محتوى المستند دفعة واحدة؟', options: ['بالضغط على Enter', 'بالنقر مرة واحدة', 'بتحديد الكل من الصفحة الرئيسية', 'لا توجد طريقة لذلك'] },
    en: { q: 'How do you select the entire document content at once?', options: ['Press Enter', 'Click once', 'Use "Select All" from the Home tab', 'There is no way to do that'] },
    fr: { q: 'Comment sélectionner tout le contenu du document en une fois ?', options: ['Appuyer sur Entrée', 'Cliquer une fois', "Utiliser « Sélectionner tout » depuis l'onglet Accueil", "Il n'y a aucun moyen de le faire"] } },

  /* ===================== LEVEL 2 ===================== */
  { level: 2, correct: 1,
    ar: { q: 'ما وظيفة "رأس وتذييل الصفحة" (Header & Footer)؟', options: ['تغيير حجم الصفحة', 'إضافة محتوى متكرر أعلى أو أسفل كل صفحة', 'حذف صفحة كاملة', 'إدراج جدول'] },
    en: { q: 'What is the "Header & Footer" feature for?', options: ['Changing the page size', 'Adding repeating content at the top or bottom of every page', 'Deleting an entire page', 'Inserting a table'] },
    fr: { q: 'À quoi sert la fonction « En-tête et pied de page » ?', options: ['Changer la taille de la page', 'Ajouter un contenu répété en haut ou en bas de chaque page', 'Supprimer une page entière', 'Insérer un tableau'] } },
  { level: 2, correct: 2,
    ar: { q: 'ما هو "فاصل الصفحة" (Page Break)؟', options: ['تلوين الصفحة', 'حذف صفحة', 'إجبار الانتقال إلى صفحة جديدة', 'تصغير الهوامش'] },
    en: { q: 'What is a "Page Break"?', options: ['Coloring the page', 'Deleting a page', 'Forcing a move to a new page', 'Shrinking the margins'] },
    fr: { q: "Qu'est-ce qu'un « Saut de page » ?", options: ['Colorer la page', 'Supprimer une page', 'Forcer le passage à une nouvelle page', 'Réduire les marges'] } },
  { level: 2, correct: 1,
    ar: { q: 'ما الغرض من ميزة "الأنماط" (Styles)؟', options: ['تغيير لغة المستند', 'تطبيق تنسيق موحد وسريع على العناوين والنصوص', 'حذف كل التنسيق', 'إدراج صور تلقائيًا'] },
    en: { q: 'What is the purpose of the "Styles" feature?', options: ['Changing the document language', 'Quickly applying consistent formatting to headings and text', 'Removing all formatting', 'Automatically inserting images'] },
    fr: { q: 'À quoi servent les « Styles » ?', options: ['Changer la langue du document', 'Appliquer rapidement une mise en forme cohérente aux titres et au texte', 'Supprimer toute la mise en forme', 'Insérer des images automatiquement'] } },
  { level: 2, correct: 2,
    ar: { q: 'ما وظيفة "التعليقات" (Comments)؟', options: ['تصحيح إملائي تلقائي', 'طباعة المستند', 'إضافة ملاحظات مرتبطة بجزء من النص دون تعديله', 'تغيير الخط'] },
    en: { q: 'What is the "Comments" feature for?', options: ['Automatic spelling correction', 'Printing the document', 'Adding notes linked to a piece of text without editing it', 'Changing the font'] },
    fr: { q: 'À quoi servent les « Commentaires » ?', options: ['Correction orthographique automatique', 'Imprimer le document', 'Ajouter des remarques liées à une partie du texte sans le modifier', 'Changer la police'] } },
  { level: 2, correct: 1,
    ar: { q: 'ما هو "فاصل الأقسام" (Section Break)؟', options: ['حذف قسم من النص', 'تقسيم المستند لأجزاء بإعدادات صفحة مختلفة لكل جزء', 'تصغير الخط', 'حفظ نسخة إضافية'] },
    en: { q: 'What is a "Section Break"?', options: ['Deleting a section of text', 'Splitting the document into parts, each with different page settings', 'Shrinking the font', 'Saving an extra copy'] },
    fr: { q: "Qu'est-ce qu'un « Saut de section » ?", options: ['Supprimer une section du texte', 'Diviser le document en parties, chacune avec des paramètres de page différents', 'Réduire la police', 'Enregistrer une copie supplémentaire'] } },
  { level: 2, correct: 2,
    ar: { q: 'ما فائدة "جدول المحتويات" التلقائي؟', options: ['طباعة قائمة الصور', 'حساب عدد الكلمات', 'إنشاء فهرس يتحدث تلقائيًا حسب العناوين', 'تلوين الجدول'] },
    en: { q: 'What is the benefit of an automatic "Table of Contents"?', options: ['Printing a list of images', 'Counting the words', 'Creating an index that updates automatically based on headings', 'Coloring the table'] },
    fr: { q: "Quel est l'intérêt d'une « Table des matières » automatique ?", options: ["Imprimer une liste d'images", 'Compter les mots', 'Créer un index qui se met à jour automatiquement selon les titres', 'Colorer le tableau'] } },
  { level: 2, correct: 2,
    ar: { q: 'ما وظيفة "العلامة المائية" (Watermark)؟', options: ['تغيير لون الخلفية بالكامل', 'إخفاء النص', 'إضافة نص أو شعار شفاف خلف محتوى الصفحة', 'الطباعة بالأبيض والأسود'] },
    en: { q: 'What does a "Watermark" do?', options: ['Change the entire background color', 'Hide the text', 'Add faded text or a logo behind the page content', 'Print in black and white'] },
    fr: { q: 'Que fait un « Filigrane » ?', options: ['Changer entièrement la couleur de fond', 'Masquer le texte', 'Ajouter un texte ou logo transparent derrière le contenu de la page', 'Imprimer en noir et blanc'] } },
  { level: 2, correct: 0,
    ar: { q: 'ما هدف وضع "القراءة" (Read Mode)؟', options: ['عرض المستند بشكل مبسط للقراءة فقط', 'الطباعة فقط', 'حذف التنسيق', 'لا فرق عن وضع الطباعة'] },
    en: { q: 'What is the purpose of "Read Mode"?', options: ['Displaying the document in a simplified view for reading only', 'Printing only', 'Removing formatting', 'No difference from print layout'] },
    fr: { q: 'À quoi sert le « Mode Lecture » ?', options: ['Afficher le document de façon simplifiée pour la lecture uniquement', 'Imprimer uniquement', 'Supprimer la mise en forme', 'Aucune différence avec le mode Page'] } },
  { level: 2, correct: 1,
    ar: { q: 'ما وظيفة "الأعمدة" (Columns) في إعداد الصفحة؟', options: ['إضافة صفوف لجدول', 'تقسيم النص لعدة أعمدة كالجرائد', 'تغيير اتجاه الصفحة', 'حذف الهوامش'] },
    en: { q: 'What do "Columns" in page setup do?', options: ['Add rows to a table', 'Split text into multiple newspaper-like columns', 'Change page orientation', 'Remove the margins'] },
    fr: { q: 'À quoi servent les « Colonnes » dans la mise en page ?', options: ['Ajouter des lignes à un tableau', 'Diviser le texte en plusieurs colonnes façon journal', "Changer l'orientation de la page", 'Supprimer les marges'] } },
  { level: 2, correct: 2,
    ar: { q: 'ما هي "الحاشية السفلية" (Footnote)؟', options: ['عنوان الصفحة', 'رأس المستند', 'ملاحظة توضيحية أسفل نفس الصفحة مرتبطة برقم بالنص', 'خط تحت النص'] },
    en: { q: 'What is a "Footnote"?', options: ['The page title', 'The document header', 'An explanatory note at the bottom of the same page linked by a number in the text', 'A line under the text'] },
    fr: { q: "Qu'est-ce qu'une « Note de bas de page » ?", options: ['Le titre de la page', "L'en-tête du document", 'Une note explicative en bas de la même page liée par un numéro dans le texte', 'Une ligne sous le texte'] } },
  { level: 2, correct: 3,
    ar: { q: 'ما فائدة أداة "التدقيق النحوي" باللغة الإنجليزية؟', options: ['تكبير الخط', 'حساب الكلمات', 'إدراج صور', 'اكتشاف الأخطاء النحوية والإملائية'] },
    en: { q: 'What is the benefit of the "Grammar Check" tool?', options: ['Increasing font size', 'Counting words', 'Inserting images', 'Detecting grammar and spelling mistakes'] },
    fr: { q: "Quel est l'intérêt de l'outil « Vérification grammaticale » ?", options: ['Augmenter la taille de police', 'Compter les mots', 'Insérer des images', "Détecter les fautes de grammaire et d'orthographe"] } },
  { level: 2, correct: 3,
    ar: { q: 'ما وظيفة "الحرف الاستهلالي الكبير" (Drop Cap)؟', options: ['تلوين كل الفقرة', 'حذف أول حرف', 'تصغير الخط', 'تكبير أول حرف من الفقرة بشكل زخرفي'] },
    en: { q: 'What does "Drop Cap" do?', options: ['Color the whole paragraph', 'Delete the first letter', 'Shrink the font', 'Decoratively enlarge the first letter of the paragraph'] },
    fr: { q: 'Que fait une « Lettrine » ?', options: ['Colorer tout le paragraphe', 'Supprimer la première lettre', 'Réduire la police', 'Agrandir la première lettre du paragraphe de façon décorative'] } },
  { level: 2, correct: 1,
    ar: { q: 'ما فائدة ميزة "التفاف النص" حول الصور؟', options: ['تغيير حجم الصورة', 'تحديد كيفية التفاف النص حول صورة أو كائن', 'حذف الصورة', 'تلوين النص'] },
    en: { q: 'What is the benefit of "Text Wrapping" around images?', options: ['Resizing the image', 'Controlling how text wraps around an image or object', 'Deleting the image', 'Coloring the text'] },
    fr: { q: "Quel est l'intérêt de l'« Habillage du texte » autour des images ?", options: ["Redimensionner l'image", "Contrôler la façon dont le texte s'enroule autour d'une image ou d'un objet", "Supprimer l'image", 'Colorer le texte'] } },
  { level: 2, correct: 2,
    ar: { q: 'ما وظيفة "الروابط التشعبية" (Hyperlinks)؟', options: ['تلوين النص فقط', 'تكبير الخط', 'ربط نص بموقع أو ملف أو مكان آخر بالمستند', 'حذف الفقرة'] },
    en: { q: 'What are "Hyperlinks" for?', options: ['Just coloring text', 'Increasing font size', 'Linking text to a website, file, or another place in the document', 'Deleting a paragraph'] },
    fr: { q: 'À quoi servent les « Liens hypertextes » ?', options: ['Uniquement colorer le texte', 'Augmenter la taille de police', 'Lier un texte à un site, un fichier ou un autre endroit du document', 'Supprimer un paragraphe'] } },
  { level: 2, correct: 2,
    ar: { q: 'ما هو "القالب" (Template) في وورد؟', options: ['نوع خط معين', 'لون صفحة', 'نموذج مستند جاهز بتنسيق مسبق يمكن البناء عليه', 'حجم ورق محدد'] },
    en: { q: 'What is a "Template" in Word?', options: ['A specific font type', 'A page color', 'A ready-made document model with preset formatting to build on', 'A specific paper size'] },
    fr: { q: "Qu'est-ce qu'un « Modèle » dans Word ?", options: ['Un type de police spécifique', 'Une couleur de page', 'Un modèle de document prêt avec une mise en forme préréglée à personnaliser', 'Un format de papier précis'] } },

  /* ===================== LEVEL 3 ===================== */
  { level: 3, correct: 1,
    ar: { q: 'ما وظيفة "دمج المراسلات" (Mail Merge)؟', options: ['دمج ملفين وورد', 'إنشاء رسائل متعددة مخصصة من قالب واحد وقائمة بيانات', 'دمج الصور بالنص', 'دمج الجداول'] },
    en: { q: 'What is "Mail Merge" for?', options: ['Merging two Word files', 'Creating multiple personalized letters from one template and a data list', 'Merging images with text', 'Merging tables'] },
    fr: { q: 'À quoi sert le « Publipostage » (Mail Merge) ?', options: ['Fusionner deux fichiers Word', "Créer plusieurs lettres personnalisées à partir d'un modèle et d'une liste de données", 'Fusionner des images avec du texte', 'Fusionner des tableaux'] } },
  { level: 3, correct: 2,
    ar: { q: 'ما هي "الحقول" (Fields) في وورد؟', options: ['خانات الجدول', 'أنواع الخطوط', 'عناصر نائبة تعرض بيانات تتحدث تلقائيًا كالتاريخ أو رقم الصفحة', 'أحجام الصفحة'] },
    en: { q: 'What are "Fields" in Word?', options: ['Table cells', 'Font types', 'Placeholders that show data updating automatically, like the date or page number', 'Page sizes'] },
    fr: { q: 'Que sont les « Champs » dans Word ?', options: ['Des cellules de tableau', 'Des types de police', "Des espaces réservés affichant des données qui se mettent à jour automatiquement, comme la date ou le numéro de page", 'Des formats de page'] } },
  { level: 3, correct: 2,
    ar: { q: 'ما وظيفة "تتبع التغييرات" (Track Changes)؟', options: ['حذف التعديلات تلقائيًا', 'تلوين النص فقط', 'تسجيل كل التعديلات لمراجعتها وقبولها أو رفضها لاحقًا', 'حفظ نسخة احتياطية فقط'] },
    en: { q: 'What is "Track Changes" for?', options: ['Automatically deleting edits', 'Just coloring the text', 'Recording all edits to review, accept, or reject them later', 'Only saving a backup copy'] },
    fr: { q: 'À quoi sert le « Suivi des modifications » ?', options: ['Supprimer automatiquement les modifications', 'Uniquement colorer le texte', 'Enregistrer toutes les modifications pour les examiner, accepter ou refuser plus tard', 'Uniquement enregistrer une copie de secours'] } },
  { level: 3, correct: 1,
    ar: { q: 'ما الفرق بين فاصل قسم "مستمر" وفاصل قسم "من الصفحة التالية"؟', options: ['لا فرق بينهما', 'الأول يبقي بنفس الصفحة، والثاني ينتقل لصفحة جديدة', 'الأول للطباعة فقط', 'الثاني يحذف الصفحة'] },
    en: { q: 'What is the difference between a "Continuous" section break and a "Next Page" section break?', options: ['No difference at all', 'The first stays on the same page, the second moves to a new page', 'The first is only for printing', 'The second deletes the page'] },
    fr: { q: 'Quelle est la différence entre un saut de section « Continu » et « Page suivante » ?', options: ['Aucune différence', 'Le premier reste sur la même page, le second passe à une nouvelle page', "Le premier sert uniquement à l'impression", 'Le second supprime la page'] } },
  { level: 3, correct: 1,
    ar: { q: 'ما وظيفة "الأجزاء السريعة" (Quick Parts)؟', options: ['تسريع فتح الملف', 'حفظ نصوص أو عناصر جاهزة لإعادة استخدامها بسرعة', 'تصغير حجم الملف', 'حذف التنسيق'] },
    en: { q: 'What is "Quick Parts" for?', options: ['Speeding up file opening', 'Saving ready-made text or elements to reuse quickly', 'Reducing file size', 'Removing formatting'] },
    fr: { q: 'À quoi servent les « QuickPart » (Composants rapides) ?', options: ["Accélérer l'ouverture du fichier", 'Enregistrer des textes ou éléments prêts à réutiliser rapidement', 'Réduire la taille du fichier', 'Supprimer la mise en forme'] } },
  { level: 3, correct: 2,
    ar: { q: 'ما هو "المستند الرئيسي" (Master Document)؟', options: ['أول نسخة من الملف', 'نسخة محمية بكلمة مرور', 'مستند يربط عدة مستندات فرعية لإدارتها كوحدة واحدة', 'قالب افتراضي'] },
    en: { q: 'What is a "Master Document"?', options: ['The first copy of the file', 'A password-protected copy', 'A document linking several subdocuments to manage them as one unit', 'A default template'] },
    fr: { q: "Qu'est-ce qu'un « Document maître » ?", options: ['La première copie du fichier', 'Une copie protégée par mot de passe', 'Un document reliant plusieurs sous-documents pour les gérer comme une seule unité', 'Un modèle par défaut'] } },
  { level: 3, correct: 1,
    ar: { q: 'ما وظيفة أداة "مقارنة المستندات" (Compare)؟', options: ['دمج مستندين بالكامل', 'إظهار الفروقات بين نسختين من نفس المستند', 'حذف مستند قديم', 'طباعة نسختين معًا'] },
    en: { q: 'What is the "Compare" documents tool for?', options: ['Fully merging two documents', 'Showing the differences between two versions of the same document', 'Deleting an old document', 'Printing two copies together'] },
    fr: { q: 'À quoi sert l\'outil « Comparer » des documents ?', options: ['Fusionner entièrement deux documents', 'Montrer les différences entre deux versions du même document', 'Supprimer un ancien document', 'Imprimer deux copies ensemble'] } },
  { level: 3, correct: 2,
    ar: { q: 'ما هي أداة "الاقتباسات والببليوغرافيا" (Citations & Bibliography)؟', options: ['أداة تدقيق إملائي', 'أداة ترجمة', 'أداة لإدراج مراجع علمية وقائمة مصادر منسقة تلقائيًا', 'أداة رسم أشكال'] },
    en: { q: 'What is the "Citations & Bibliography" tool?', options: ['A spell-check tool', 'A translation tool', 'A tool to insert academic references and an automatically formatted source list', 'A shape-drawing tool'] },
    fr: { q: 'Qu\'est-ce que l\'outil « Citations et bibliographie » ?', options: ['Un outil de vérification orthographique', 'Un outil de traduction', 'Un outil pour insérer des références académiques et une liste de sources mises en forme automatiquement', 'Un outil de dessin de formes'] } },
  { level: 3, correct: 1,
    ar: { q: 'ما وظيفة "حماية المستند" (Protect Document)؟', options: ['تكبير الخط تلقائيًا', 'تقييد التعديل أو حماية الملف بكلمة مرور', 'حذف التنسيق', 'إخفاء الصور تلقائيًا'] },
    en: { q: 'What is "Protect Document" for?', options: ['Automatically increasing font size', 'Restricting editing or password-protecting the file', 'Removing formatting', 'Automatically hiding images'] },
    fr: { q: 'À quoi sert « Protéger le document » ?', options: ['Augmenter automatiquement la taille de police', 'Restreindre la modification ou protéger le fichier par mot de passe', 'Supprimer la mise en forme', 'Masquer automatiquement les images'] } },
  { level: 3, correct: 0,
    ar: { q: 'متى يظهر "وضع التوافق" (Compatibility Mode)؟', options: ['عند فتح ملف بصيغة أقدم لضمان توافقه', 'لتصغير حجم الملف', 'للطباعة فقط', 'لتغيير لغة المستند'] },
    en: { q: 'When does "Compatibility Mode" appear?', options: ['When opening a file in an older format to ensure compatibility', 'To reduce file size', 'Only for printing', 'To change the document language'] },
    fr: { q: 'Quand apparaît le « Mode de compatibilité » ?', options: ['Lors de l\'ouverture d\'un fichier au format plus ancien pour garantir sa compatibilité', 'Pour réduire la taille du fichier', "Uniquement pour l'impression", 'Pour changer la langue du document'] } },
  { level: 3, correct: 1,
    ar: { q: 'ما فائدة ربط عدة "إطارات نصية" (Text Boxes) ببعضها؟', options: ['تكبير الصور فقط', 'ليتدفق النص تلقائيًا بين الصناديق المرتبطة', 'حذف النص', 'تغيير الخط فقط'] },
    en: { q: 'What is the benefit of linking several "Text Boxes" together?', options: ['Only enlarging images', 'So the text flows automatically between linked boxes', 'Deleting the text', 'Only changing the font'] },
    fr: { q: 'Quel est l\'intérêt de lier plusieurs « Zones de texte » entre elles ?', options: ['Uniquement agrandir les images', "Pour que le texte s'écoule automatiquement entre les zones liées", 'Supprimer le texte', 'Uniquement changer la police'] } },
  { level: 3, correct: 1,
    ar: { q: 'ما وظيفة "معالج المغلفات والملصقات" (Envelopes & Labels)؟', options: ['تصميم غلاف كتاب', 'طباعة عناوين على مغلفات أو ملصقات بشكل منظم', 'إدراج صورة مغلف', 'حفظ كملصق PDF'] },
    en: { q: 'What is the "Envelopes & Labels" wizard for?', options: ['Designing a book cover', 'Printing addresses on envelopes or labels in an organized way', 'Inserting an envelope picture', 'Saving as a PDF label'] },
    fr: { q: 'À quoi sert l\'assistant « Enveloppes et étiquettes » ?', options: ['Concevoir une couverture de livre', 'Imprimer des adresses sur des enveloppes ou étiquettes de façon organisée', "Insérer une image d'enveloppe", 'Enregistrer en étiquette PDF'] } },
  { level: 3, correct: 1,
    ar: { q: 'ما وظيفة "الارتباطات المرجعية" (Cross-references)؟', options: ['ربط بموقع خارجي', 'الإشارة تلقائيًا لعنصر آخر بالمستند وتحديثها عند تغييره', 'حذف الروابط', 'تكبير الخط'] },
    en: { q: 'What are "Cross-references" for?', options: ['Linking to an external website', 'Automatically referencing another element in the document and updating it if it changes', 'Deleting links', 'Increasing font size'] },
    fr: { q: 'À quoi servent les « Renvois » (Cross-references) ?', options: ['Lier vers un site externe', "Faire référence automatiquement à un autre élément du document et se mettre à jour s'il change", 'Supprimer des liens', 'Augmenter la taille de police'] } },
  { level: 3, correct: 1,
    ar: { q: 'ما هو "جدول الأشكال" (Table of Figures)؟', options: ['قائمة بالألوان المستخدمة', 'قائمة تلقائية بكل الأشكال أو الجداول مع أرقام صفحاتها', 'قائمة بالخطوط', 'قائمة بالمؤلفين'] },
    en: { q: 'What is a "Table of Figures"?', options: ['A list of colors used', 'An automatic list of all figures or tables with their page numbers', 'A list of fonts', 'A list of authors'] },
    fr: { q: "Qu'est-ce qu'une « Table des illustrations » ?", options: ['Une liste des couleurs utilisées', 'Une liste automatique de toutes les figures ou tableaux avec leurs numéros de page', 'Une liste de polices', "Une liste d'auteurs"] } },
  { level: 3, correct: 2,
    ar: { q: 'ما وظيفة ميزة "الإملاء" (Dictate) في وورد؟', options: ['قراءة النص بصوت عالٍ', 'ترجمة النص', 'تحويل الكلام المنطوق إلى نص مكتوب مباشرة', 'تدقيق إملائي فقط'] },
    en: { q: 'What does the "Dictate" feature do in Word?', options: ['Reading the text aloud', 'Translating the text', 'Converting spoken words directly into written text', 'Only spell-checking'] },
    fr: { q: 'Que fait la fonction « Dicter » dans Word ?', options: ['Lire le texte à voix haute', 'Traduire le texte', 'Convertir directement la parole en texte écrit', "Uniquement vérifier l'orthographe"] } },

  /* ===================== LEVEL 4 ===================== */
  { level: 4, correct: 1,
    ar: { q: 'ما هي "وحدات الماكرو" (Macros)؟', options: ['نوع خط خاص', 'مجموعة أوامر مسجّلة تُنفَّذ تلقائيًا لأتمتة المهام المتكررة', 'إضافة صورة متحركة', 'أداة طباعة متقدمة'] },
    en: { q: 'What are "Macros"?', options: ['A special font type', 'A set of recorded commands run automatically to automate repetitive tasks', 'Adding an animated image', 'An advanced printing tool'] },
    fr: { q: 'Que sont les « Macros » ?', options: ['Un type de police spécial', 'Un ensemble de commandes enregistrées exécutées automatiquement pour automatiser des tâches répétitives', 'Ajouter une image animée', "Un outil d'impression avancé"] } },
  { level: 4, correct: 0,
    ar: { q: 'ما لغة البرمجة المستخدمة لكتابة الماكرو في وورد؟', options: ['VBA', 'Python', 'JavaScript', 'C++'] },
    en: { q: 'What programming language is used to write macros in Word?', options: ['VBA', 'Python', 'JavaScript', 'C++'] },
    fr: { q: 'Quel langage de programmation sert à écrire les macros dans Word ?', options: ['VBA', 'Python', 'JavaScript', 'C++'] } },
  { level: 4, correct: 2,
    ar: { q: 'ما وظيفة تحديث الحقول يدويًا بمفتاح F9؟', options: ['حذف الحقل', 'تجميد الحقل', 'تحديث قيمة الحقل لتعكس آخر البيانات', 'تلوين الحقل'] },
    en: { q: 'What does manually updating a field with F9 do?', options: ['Delete the field', 'Freeze the field', "Update the field's value to reflect the latest data", 'Color the field'] },
    fr: { q: "Que fait la mise à jour manuelle d'un champ avec F9 ?", options: ['Supprimer le champ', 'Figer le champ', 'Mettre à jour la valeur du champ pour refléter les dernières données', 'Colorer le champ'] } },
  { level: 4, correct: 1,
    ar: { q: 'ما هو "السبايك" (Spike) في وورد؟', options: ['نوع تنسيق للجدول', 'أداة لجمع عدة مقاطع نص من أماكن مختلفة ولصقها دفعة واحدة', 'أداة رسم', 'نوع خط خاص'] },
    en: { q: 'What is "Spike" in Word?', options: ['A table formatting style', 'A tool to collect several text pieces from different places and paste them all at once', 'A drawing tool', 'A special font type'] },
    fr: { q: 'Qu\'est-ce que le « Spike » (Collecteur) dans Word ?', options: ['Un style de mise en forme de tableau', "Un outil pour rassembler plusieurs extraits de texte de différents endroits et les coller en une fois", 'Un outil de dessin', 'Un type de police spécial'] } },
  { level: 4, correct: 1,
    ar: { q: 'ما وظيفة "جزء التنقل" (Navigation Pane)؟', options: ['تكبير الخط', 'عرض هيكل العناوين للتنقل السريع بالمستند الطويل', 'حذف الصفحات', 'تلوين النص'] },
    en: { q: 'What is the "Navigation Pane" for?', options: ['Increasing font size', 'Showing the heading structure for quick navigation in a long document', 'Deleting pages', 'Coloring text'] },
    fr: { q: 'À quoi sert le « Volet de navigation » ?', options: ['Augmenter la taille de police', 'Afficher la structure des titres pour naviguer rapidement dans un long document', 'Supprimer des pages', 'Colorer le texte'] } },
  { level: 4, correct: 2,
    ar: { q: 'ما الفرق بين "النمط" (Style) و"السمة" (Theme)؟', options: ['لا فرق بينهما', 'السمة للطباعة فقط', 'النمط لتنسيق عنصر نصي محدد، والسمة تغيّر ألوان وخطوط المستند كله', 'النمط يحذف التنسيق'] },
    en: { q: 'What is the difference between a "Style" and a "Theme"?', options: ['No difference at all', 'A theme is only for printing', 'A style formats a specific text element, while a theme changes the colors and fonts of the whole document', 'A style deletes formatting'] },
    fr: { q: 'Quelle est la différence entre un « Style » et un « Thème » ?', options: ['Aucune différence', "Le thème sert uniquement à l'impression", 'Un style met en forme un élément de texte précis, un thème change les couleurs et polices de tout le document', 'Un style supprime la mise en forme'] } },
  { level: 4, correct: 2,
    ar: { q: 'ما وظيفة علامات التبويب المخصصة (Tab Stops) على المسطرة؟', options: ['تغيير حجم الصفحة', 'إدراج جدول', 'التحكم الدقيق بمحاذاة النص عند الضغط على Tab', 'حذف الهوامش'] },
    en: { q: 'What are custom "Tab Stops" on the ruler for?', options: ['Changing the page size', 'Inserting a table', 'Precisely controlling text alignment when pressing Tab', 'Removing the margins'] },
    fr: { q: 'À quoi servent les « Taquets de tabulation » personnalisés sur la règle ?', options: ['Changer la taille de la page', 'Insérer un tableau', 'Contrôler précisément l\'alignement du texte en appuyant sur Tab', 'Supprimer les marges'] } },
  { level: 4, correct: 1,
    ar: { q: 'ما فائدة ميزة "التحكم بالفقرات اليتيمة والأرملة" (Widow/Orphan Control)؟', options: ['نوع تنسيق خط', 'منع ظهور سطر وحيد من فقرة في أعلى أو أسفل صفحة منفصلة', 'أداة حذف الفقرات', 'أداة تكبير النص'] },
    en: { q: 'What is the benefit of "Widow/Orphan Control"?', options: ['A font formatting type', 'Preventing a single line of a paragraph from appearing alone at the top or bottom of a separate page', 'A paragraph-deleting tool', 'A text-enlarging tool'] },
    fr: { q: 'Quel est l\'intérêt du « Contrôle des lignes veuves et orphelines » ?', options: ['Un type de mise en forme de police', "Empêcher une seule ligne d'un paragraphe d'apparaître isolée en haut ou en bas d'une page séparée", 'Un outil de suppression de paragraphes', "Un outil d'agrandissement du texte"] } },
  { level: 4, correct: 1,
    ar: { q: 'ما وظيفة "أداة التحقق من إمكانية الوصول" (Accessibility Checker)؟', options: ['فحص الأخطاء الإملائية', 'فحص المستند للتأكد من سهولة استخدامه لذوي الإعاقة', 'فحص حجم الملف', 'فحص الطباعة'] },
    en: { q: 'What is the "Accessibility Checker" tool for?', options: ['Checking spelling mistakes', 'Checking the document to ensure it is easy to use for people with disabilities', 'Checking file size', 'Checking printing'] },
    fr: { q: 'À quoi sert le « Vérificateur d\'accessibilité » ?', options: ['Vérifier les fautes d\'orthographe', 'Vérifier que le document est facile à utiliser pour les personnes en situation de handicap', 'Vérifier la taille du fichier', "Vérifier l'impression"] } },
  { level: 4, correct: 2,
    ar: { q: 'ما فائدة "النص البديل" (Alt Text) للصور؟', options: ['عنوان الصورة فقط', 'حجم الصورة', 'وصف نصي للصورة يقرأه قارئ الشاشة لذوي الإعاقة البصرية', 'نوع ملف الصورة'] },
    en: { q: 'What is the benefit of "Alt Text" for images?', options: ['Just the image title', 'The image size', 'A text description of the image read by screen readers for visually impaired users', 'The image file type'] },
    fr: { q: 'Quel est l\'intérêt du « Texte de remplacement » (Alt Text) pour les images ?', options: ["Uniquement le titre de l'image", "La taille de l'image", 'Une description textuelle de l\'image lue par les lecteurs d\'écran pour les malvoyants', "Le type de fichier de l'image"] } },
  { level: 4, correct: 2,
    ar: { q: 'ما وظيفة "التحقق من التوافق" (Compatibility Checker)؟', options: ['فحص الأخطاء الإملائية', 'فحص الفيروسات', 'التأكد أن الميزات المستخدمة تعمل بإصدارات وورد الأقدم', 'فحص حجم الخط'] },
    en: { q: 'What is the "Compatibility Checker" for?', options: ['Checking spelling mistakes', 'Checking for viruses', 'Making sure the features used work with older Word versions', 'Checking font size'] },
    fr: { q: 'À quoi sert le « Vérificateur de compatibilité » ?', options: ['Vérifier les fautes d\'orthographe', 'Vérifier les virus', 'S\'assurer que les fonctionnalités utilisées fonctionnent avec des versions plus anciennes de Word', 'Vérifier la taille de la police'] } },
  { level: 4, correct: 2,
    ar: { q: 'ما هي "الفهرسة" (Index) في نهاية المستند؟', options: ['قائمة بالمراجع', 'قائمة بالصور', 'قائمة أبجدية بالمصطلحات المهمة وأرقام صفحاتها', 'قائمة بالمؤلفين'] },
    en: { q: 'What is an "Index" at the end of a document?', options: ['A list of references', 'A list of images', 'An alphabetical list of important terms with their page numbers', 'A list of authors'] },
    fr: { q: "Qu'est-ce qu'un « Index » à la fin d'un document ?", options: ['Une liste de références', 'Une liste d\'images', 'Une liste alphabétique de termes importants avec leurs numéros de page', "Une liste d'auteurs"] } },
  { level: 4, correct: 2,
    ar: { q: 'ما وظيفة "تقسيم الكلمات" (Hyphenation) التلقائي؟', options: ['حذف المسافات', 'تكبير الخط', 'تقسيم الكلمات الطويلة تلقائيًا بنهاية السطر لتحسين المحاذاة', 'تلوين النص'] },
    en: { q: 'What does automatic "Hyphenation" do?', options: ['Delete spaces', 'Increase font size', 'Automatically split long words at the end of a line to improve alignment', 'Color the text'] },
    fr: { q: 'Que fait la « Coupure de mots » (Hyphenation) automatique ?', options: ['Supprimer les espaces', 'Augmenter la taille de police', 'Couper automatiquement les mots longs en fin de ligne pour améliorer l\'alignement', 'Colorer le texte'] } },
  { level: 4, correct: 2,
    ar: { q: 'ما فائدة ميزة "استعادة المستندات غير المحفوظة"؟', options: ['استرجاع ملفات محذوفة نهائيًا', 'استرجاع كلمة المرور', 'استرجاع مستندات أُغلقت دون حفظ من نسخ مؤقتة محفوظة تلقائيًا', 'استرجاع الخط الأصلي'] },
    en: { q: 'What is the benefit of "Recover Unsaved Documents"?', options: ['Recovering permanently deleted files', 'Recovering a password', 'Recovering documents closed without saving, from automatically saved temporary copies', 'Recovering the original font'] },
    fr: { q: 'Quel est l\'intérêt de « Récupérer des documents non enregistrés » ?', options: ['Récupérer des fichiers supprimés définitivement', 'Récupérer un mot de passe', 'Récupérer des documents fermés sans enregistrement, à partir de copies temporaires automatiques', "Récupérer la police d'origine"] } },
  { level: 4, correct: 2,
    ar: { q: 'ما هي "الوثيقة الفرعية" (Subdocument) داخل المستند الرئيسي؟', options: ['نسخة احتياطية', 'قالب فرعي', 'مستند منفصل مرتبط بالمستند الرئيسي يمكن تحريره بشكل مستقل', 'صفحة إضافية فقط'] },
    en: { q: 'What is a "Subdocument" inside a master document?', options: ['A backup copy', 'A sub-template', 'A separate document linked to the master document that can be edited independently', 'Just an extra page'] },
    fr: { q: "Qu'est-ce qu'un « Sous-document » à l'intérieur d'un document maître ?", options: ['Une copie de secours', 'Un sous-modèle', 'Un document séparé lié au document maître pouvant être modifié indépendamment', 'Juste une page supplémentaire'] } },

  /* ===================== LEVEL 5 ===================== */
  { level: 5, correct: 1,
    ar: { q: 'ما وظيفة "محرر المعادلات" الذي يُفتح بالاختصار Alt+=؟', options: ['رسم أشكال هندسية', 'كتابة معادلات رياضية بتنسيق احترافي', 'إدراج جداول رياضية', 'حساب المعادلات تلقائيًا'] },
    en: { q: 'What is the "Equation Editor", opened with Alt+=, for?', options: ['Drawing geometric shapes', 'Writing math equations with professional formatting', 'Inserting math tables', 'Automatically solving equations'] },
    fr: { q: 'À quoi sert l\'« Éditeur d\'équations », ouvert avec Alt+= ?', options: ['Dessiner des formes géométriques', 'Écrire des équations mathématiques avec une mise en forme professionnelle', 'Insérer des tableaux mathématiques', 'Résoudre automatiquement les équations'] } },
  { level: 5, correct: 1,
    ar: { q: 'ما وظيفة حقول "IF" الشرطية في دمج المراسلات؟', options: ['حذف السجلات الفارغة', 'عرض نص مختلف حسب شرط معين بالبيانات لكل رسالة', 'تصفية المستلمين فقط', 'ترتيب الأسماء أبجديًا'] },
    en: { q: 'What are conditional "IF" fields in Mail Merge for?', options: ['Deleting empty records', 'Showing different text based on a condition in the data for each letter', 'Only filtering recipients', 'Sorting names alphabetically'] },
    fr: { q: 'À quoi servent les champs conditionnels « IF » dans le publipostage ?', options: ['Supprimer les enregistrements vides', 'Afficher un texte différent selon une condition dans les données pour chaque lettre', 'Uniquement filtrer les destinataires', 'Trier les noms par ordre alphabétique'] } },
  { level: 5, correct: 1,
    ar: { q: 'ما فائدة الارتباط الديناميكي (OLE) عند إدراج جدول إكسل داخل وورد؟', options: ['نسخ الجدول كصورة ثابتة فقط', 'ربط الجدول بحيث يتحدث تلقائيًا عند تعديل ملف إكسل الأصلي', 'تحويل الجدول لنص عادي', 'حذف الجدول تلقائيًا'] },
    en: { q: 'What is the benefit of dynamic linking (OLE) when inserting an Excel table into Word?', options: ['Just copying the table as a static image', 'Linking the table so it updates automatically when the original Excel file changes', 'Converting the table into plain text', 'Automatically deleting the table'] },
    fr: { q: "Quel est l'intérêt de la liaison dynamique (OLE) lors de l'insertion d'un tableau Excel dans Word ?", options: ['Copier simplement le tableau comme image statique', "Lier le tableau pour qu'il se mette à jour automatiquement quand le fichier Excel d'origine change", 'Convertir le tableau en texte brut', 'Supprimer automatiquement le tableau'] } },
  { level: 5, correct: 2,
    ar: { q: 'ما وظيفة "القوائم متعددة المستويات" المرتبطة بأنماط العناوين؟', options: ['قائمة نقطية بسيطة', 'قائمة بالصور', 'ترقيم تلقائي هرمي يتبع مستويات العناوين (1، 1.1، 1.1.1)', 'قائمة بالألوان'] },
    en: { q: 'What do "Multilevel Lists" linked to heading styles do?', options: ['A simple bullet list', 'A list of images', 'Automatic hierarchical numbering following heading levels (1, 1.1, 1.1.1)', 'A list of colors'] },
    fr: { q: 'Que font les « Listes à plusieurs niveaux » liées aux styles de titre ?', options: ['Une simple liste à puces', "Une liste d'images", 'Une numérotation hiérarchique automatique suivant les niveaux de titre (1, 1.1, 1.1.1)', 'Une liste de couleurs'] } },
  { level: 5, correct: 1,
    ar: { q: 'ما وظيفة "محرر Visual Basic" الذي يُفتح بالاختصار Alt+F11؟', options: ['محرر نصوص عادي', 'بيئة كتابة وتعديل أكواد الماكرو مباشرة', 'أداة تصميم صفحات', 'أداة طباعة متقدمة'] },
    en: { q: 'What is the "Visual Basic Editor", opened with Alt+F11, for?', options: ['A plain text editor', 'An environment to write and edit macro code directly', 'A page design tool', 'An advanced printing tool'] },
    fr: { q: 'À quoi sert l\'« Éditeur Visual Basic », ouvert avec Alt+F11 ?', options: ['Un simple éditeur de texte', 'Un environnement pour écrire et modifier directement le code des macros', 'Un outil de conception de pages', "Un outil d'impression avancé"] } },
  { level: 5, correct: 1,
    ar: { q: 'ما الفرق بين حقل REF وحقل PAGEREF في نظام الحقول؟', options: ['لا فرق بينهما', 'REF يشير لنص أو محتوى، وPAGEREF يشير لرقم الصفحة فقط', 'REF للصور فقط', 'PAGEREF للجداول فقط'] },
    en: { q: 'What is the difference between the REF and PAGEREF fields?', options: ['No difference at all', 'REF refers to text or content, while PAGEREF refers only to the page number', 'REF is only for images', 'PAGEREF is only for tables'] },
    fr: { q: 'Quelle est la différence entre les champs REF et PAGEREF ?', options: ['Aucune différence', 'REF renvoie à un texte ou contenu, alors que PAGEREF renvoie uniquement au numéro de page', 'REF est réservé aux images', 'PAGEREF est réservé aux tableaux'] } },
  { level: 5, correct: 2,
    ar: { q: 'ما وظيفة تقييد التعديل لإنشاء نموذج قابل للتعبئة (Filling in Forms)؟', options: ['منع الطباعة كليًا', 'منع النسخ كليًا', 'السماح بالتعديل فقط في حقول محددة كنموذج قابل للتعبئة', 'منع الحفظ نهائيًا'] },
    en: { q: 'What does restricting editing to "Filling in Forms" do?', options: ['Completely block printing', 'Completely block copying', 'Allow editing only in specific fields, like a fillable form', 'Completely block saving'] },
    fr: { q: 'Que fait la restriction de modification en mode « Remplissage de formulaires » ?', options: ["Bloquer entièrement l'impression", 'Bloquer entièrement la copie', 'N\'autoriser la modification que dans des champs précis, comme un formulaire à remplir', "Bloquer entièrement l'enregistrement"] } },
  { level: 5, correct: 2,
    ar: { q: 'ما ميزة "الأنماط المرتبطة" (Linked Styles) مقارنة بنمط الفقرة العادي؟', options: ['تعمل فقط على الفقرات', 'تعمل فقط على الجداول', 'يمكن تطبيقها كنمط فقرة أو نمط حرف حسب طريقة التحديد', 'لا يمكن تعديلها إطلاقًا'] },
    en: { q: 'What is the advantage of "Linked Styles" compared to a regular paragraph style?', options: ['They only work on paragraphs', 'They only work on tables', 'They can act as a paragraph style or a character style depending on the selection', 'They can never be edited'] },
    fr: { q: 'Quel est l\'avantage des « Styles liés » par rapport à un style de paragraphe classique ?', options: ['Ils ne fonctionnent que sur les paragraphes', 'Ils ne fonctionnent que sur les tableaux', 'Ils peuvent agir comme style de paragraphe ou de caractère selon la sélection', 'Ils ne peuvent jamais être modifiés'] } },
  { level: 5, correct: 1,
    ar: { q: 'ما وظيفة حقل "SEQ" (Sequence Field) في ترقيم الأشكال والجداول؟', options: ['ترقيم الصفحات فقط', 'توليد ترقيم متسلسل تلقائي يتحدث عند إضافة أو حذف عناصر', 'ترقيم الأسطر فقط', 'ترقيم الفقرات فقط'] },
    en: { q: 'What is the "SEQ" (Sequence) field used for in numbering figures and tables?', options: ['Only numbering pages', 'Generating automatic sequential numbering that updates when items are added or removed', 'Only numbering lines', 'Only numbering paragraphs'] },
    fr: { q: 'À quoi sert le champ « SEQ » (Séquence) pour numéroter figures et tableaux ?', options: ['Uniquement numéroter les pages', "Générer une numérotation séquentielle automatique qui se met à jour lors de l'ajout ou la suppression d'éléments", 'Uniquement numéroter les lignes', 'Uniquement numéroter les paragraphes'] } },
  { level: 5, correct: 2,
    ar: { q: 'ما فائدة "التوقيع الرقمي" (Digital Signature) في حماية المستندات؟', options: ['توقيع بخط اليد الممسوح ضوئيًا فقط', 'كلمة مرور فقط', 'إثبات هوية الموقّع وسلامة المستند من التعديل بعد التوقيع', 'ختم صورة فقط'] },
    en: { q: 'What is the benefit of a "Digital Signature" in protecting documents?', options: ['Just a scanned handwritten signature', 'Just a password', "Proving the signer's identity and that the document was not altered after signing", 'Just an image stamp'] },
    fr: { q: 'Quel est l\'intérêt de la « Signature numérique » pour protéger les documents ?', options: ['Uniquement une signature manuscrite scannée', 'Uniquement un mot de passe', "Prouver l'identité du signataire et l'intégrité du document après signature", 'Uniquement un tampon image'] } },
  { level: 5, correct: 2,
    ar: { q: 'ما وظيفة خيار "فتح وإصلاح" (Open and Repair)؟', options: ['حذف الملف التالف', 'ضغط حجم الملف', 'محاولة إصلاح واسترجاع محتوى ملف وورد تالف أو معطوب', 'تحويل صيغة الملف فقط'] },
    en: { q: 'What is the "Open and Repair" option for?', options: ['Deleting a corrupted file', 'Compressing the file size', 'Trying to fix and recover the content of a damaged or corrupted Word file', 'Only converting the file format'] },
    fr: { q: "À quoi sert l'option « Ouvrir et réparer » ?", options: ['Supprimer un fichier corrompu', 'Compresser la taille du fichier', "Tenter de réparer et récupérer le contenu d'un fichier Word endommagé", 'Uniquement convertir le format du fichier'] } },
  { level: 5, correct: 2,
    ar: { q: 'ما هي "عناصر التحكم بالمحتوى" (Content Controls) في النماذج المتقدمة؟', options: ['صور فقط', 'جداول فقط', 'عناصر تفاعلية كصناديق نص أو قوائم منسدلة يمكن التحكم بسلوكها بالنموذج', 'روابط فقط'] },
    en: { q: 'What are "Content Controls" in advanced forms?', options: ['Just images', 'Just tables', 'Interactive elements like text boxes or dropdown lists whose behavior can be controlled in the form', 'Just links'] },
    fr: { q: 'Que sont les « Contrôles de contenu » dans les formulaires avancés ?', options: ['Uniquement des images', 'Uniquement des tableaux', 'Des éléments interactifs comme des zones de texte ou des listes déroulantes dont on peut contrôler le comportement dans le formulaire', 'Uniquement des liens'] } },
  { level: 5, correct: 1,
    ar: { q: 'ما وظيفة قاعدة "Skip Record If" في دمج المراسلات المتقدم؟', options: ['حذف السجل نهائيًا من الملف', 'تجاهل سجلات معينة من قائمة البيانات أثناء الدمج بناءً على شرط', 'دمج سجلين ببعض', 'ترتيب السجلات فقط'] },
    en: { q: 'What is the "Skip Record If" rule for in advanced Mail Merge?', options: ['Permanently deleting the record from the file', 'Skipping certain records from the data list during the merge based on a condition', 'Merging two records together', 'Only sorting records'] },
    fr: { q: 'À quoi sert la règle « Skip Record If » dans un publipostage avancé ?', options: ["Supprimer définitivement l'enregistrement du fichier", 'Ignorer certains enregistrements de la liste de données pendant la fusion selon une condition', 'Fusionner deux enregistrements ensemble', 'Uniquement trier les enregistrements'] } },
  { level: 5, correct: 2,
    ar: { q: 'ما الغرض من تنسيق Open XML الذي تعتمد عليه صيغة .docx؟', options: ['تشفير الملف بكلمة مرور فقط', 'ضغط الصور فقط', 'تخزين المستند كملف مضغوط يحتوي XML منظم لسهولة القراءة والتوافق', 'حماية الملف من الفيروسات'] },
    en: { q: 'What is the purpose of the Open XML format that .docx is based on?', options: ['Only encrypting the file with a password', 'Only compressing images', 'Storing the document as a compressed file containing structured XML for readability and compatibility', 'Protecting the file from viruses'] },
    fr: { q: 'Quel est l\'objectif du format Open XML sur lequel repose le .docx ?', options: ['Uniquement chiffrer le fichier avec un mot de passe', 'Uniquement compresser les images', 'Stocker le document comme un fichier compressé contenant du XML structuré pour la lisibilité et la compatibilité', 'Protéger le fichier contre les virus'] } },
  { level: 5, correct: 1,
    ar: { q: 'ما فائدة "الأنماط السريعة" (Style Sets) في تبويب التصميم؟', options: ['تغيير لغة المستند بالكامل', 'تطبيق مجموعة تنسيقات متجانسة (خطوط وألوان) على كل عناوين ونصوص المستند دفعة واحدة', 'حذف كل الأنماط', 'تكبير الصفحة فقط'] },
    en: { q: 'What is the benefit of "Style Sets" in the Design tab?', options: ['Changing the entire document language', 'Applying a coordinated set of formats (fonts and colors) to all headings and text at once', 'Deleting all styles', 'Only enlarging the page'] },
    fr: { q: 'Quel est l\'intérêt des « Jeux de styles » dans l\'onglet Création ?', options: ['Changer entièrement la langue du document', 'Appliquer d\'un coup un ensemble cohérent de mises en forme (polices et couleurs) à tous les titres et textes', 'Supprimer tous les styles', 'Uniquement agrandir la page'] } },
];
