// ============================================================
// templates.js — email templates and the complete example message
// shown for each one (ar / fr / en). The example only fills the
// preview while a field is empty; it is never stored.
// purpose: the value sent to the draftEmail function (same keys as before)
// ============================================================
window.MAIL_CATS = ['req', 'follow', 'rel', 'career'];

window.MAIL_TEMPLATES = [
  { id: 'info', cat: 'req', purpose: 'request', color: '#2F6F9F', icon: '<circle cx="12" cy="12" r="9"/><path d="M12 11v5M12 8h.01"/>',
    name: { ar: 'طلب معلومات', fr: "Demande d'informations", en: 'Information request' } },
  { id: 'quote', cat: 'req', purpose: 'request', color: '#0891B2', icon: '<path d="M6 3h9l4 4v14H6z"/><path d="M9 12h6M9 16h4M14 3v5h5"/>',
    name: { ar: 'طلب عرض سعر', fr: 'Demande de devis', en: 'Quote request' } },
  { id: 'meeting', cat: 'req', purpose: 'request', color: '#7C3AED', icon: '<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M3 10h18M8 3v4M16 3v4"/>',
    name: { ar: 'طلب اجتماع', fr: 'Demande de réunion', en: 'Meeting request' } },
  { id: 'followup', cat: 'follow', purpose: 'followup', color: '#D97706', icon: '<path d="M4 12a8 8 0 1 0 3-6.2"/><path d="M4 4v5h5"/>',
    name: { ar: 'متابعة', fr: 'Relance', en: 'Follow-up' } },
  { id: 'reply', cat: 'follow', purpose: 'other', color: '#0F766E', icon: '<path d="M10 9L5 13l5 4"/><path d="M5 13h9a5 5 0 0 1 5 5v1"/>',
    name: { ar: 'رد على عميل', fr: 'Réponse à un client', en: 'Reply to a client' } },
  { id: 'sendfile', cat: 'follow', purpose: 'other', color: '#4338CA', icon: '<path d="M21 12l-8.5 8.5a5 5 0 0 1-7-7L14 5a3.5 3.5 0 0 1 5 5l-8.5 8.5a2 2 0 0 1-3-3L15 8"/>',
    name: { ar: 'إرسال ملف', fr: "Envoi d'un fichier", en: 'Sending a file' } },
  { id: 'complaint', cat: 'rel', purpose: 'complaint', color: '#C0392B', icon: '<path d="M12 9v4M12 17h.01"/><path d="M10.3 3.9L1.8 18a2 2 0 0 0 1.7 3h17a2 2 0 0 0 1.7-3L13.7 3.9a2 2 0 0 0-3.4 0z"/>',
    name: { ar: 'شكوى', fr: 'Réclamation', en: 'Complaint' } },
  { id: 'apology', cat: 'rel', purpose: 'apology', color: '#64748B', icon: '<circle cx="12" cy="12" r="9"/><path d="M8 15c1.2-1.3 2.5-2 4-2s2.8.7 4 2M9 9h.01M15 9h.01"/>',
    name: { ar: 'اعتذار', fr: 'Excuses', en: 'Apology' } },
  { id: 'thanks', cat: 'rel', purpose: 'thanks', color: '#16A34A', icon: '<path d="M12 21s-7-4.5-9-9a5 5 0 0 1 9-3 5 5 0 0 1 9 3c-2 4.5-9 9-9 9z"/>',
    name: { ar: 'شكر', fr: 'Remerciements', en: 'Thank-you' } },
  { id: 'leave', cat: 'career', purpose: 'request', color: '#DB2777', icon: '<circle cx="12" cy="12" r="4"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M5 19l2-2M17 7l2-2"/>',
    name: { ar: 'طلب إجازة', fr: 'Demande de congé', en: 'Leave request' } },
  { id: 'application', cat: 'career', purpose: 'intro', color: '#1E40AF', icon: '<rect x="3" y="7" width="18" height="13" rx="2"/><path d="M9 7V5a2 2 0 0 1 2-2h2a2 2 0 0 1 2 2v2M3 13h18"/>',
    name: { ar: 'ترشح لوظيفة', fr: 'Candidature', en: 'Job application' } },
  { id: 'intro', cat: 'career', purpose: 'intro', color: '#B45309', icon: '<circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/>',
    name: { ar: 'تقديم نفسك', fr: 'Présentation', en: 'Introducing yourself' } },
  { id: 'free', cat: '', purpose: 'other', color: '#475569', icon: '<path d="M4 20h4L19 9l-4-4L4 16z"/><path d="M13 7l4 4"/>',
    name: { ar: 'رسالة حرّة', fr: 'Message libre', en: 'Free message' } },
];

// sender shown while the sender section is empty
window.MAIL_EXAMPLE_SENDER = {
  ar: { name: 'سفيان مرابطي', job: 'رئيس مكتب الدراسات والصيانة', org: 'مصنع الإسمنت — بشار', email: 's.merabti@ciment.dz', phone: '0555 12 34 56', extra: '' },
  fr: { name: 'Sofiane Merabti', job: "Chef du bureau d'études et maintenance", org: 'Cimenterie de Béchar', email: 's.merabti@ciment.dz', phone: '0555 12 34 56', extra: '' },
  en: { name: 'Sofiane Merabti', job: 'Head of Engineering & Maintenance', org: 'Béchar Cement Plant', email: 's.merabti@ciment.dz', phone: '+213 555 12 34 56', extra: '' },
};

// to: [name, title, organization, email]
window.MAIL_EXAMPLES = {
  info: {
    ar: { to: ['ليلى عمراني', 'مسؤولة المبيعات', 'شركة الأطلس للتجهيزات الصناعية', 'l.amrani@atlas-equip.dz'],
      subject: 'طلب معلومات تقنية حول المحركات الكهربائية 75 كيلوواط',
      points: 'نريد البطاقة التقنية، الكفاءة الطاقوية، آجال التسليم، والضمان للمحركات 75 كيلوواط.',
      body: 'السيدة ليلى عمراني المحترمة،\n\nتحية طيبة وبعد،\n\nنحن بصدد تجديد جزء من المحركات الكهربائية في خط الطحن بمصنعنا، ونرغب في الحصول على معلومات تقنية حول المحركات ذات القدرة 75 كيلوواط التي تقترحونها، ولا سيما:\n- البطاقة التقنية ودرجة الكفاءة الطاقوية (IE3 أو IE4)،\n- آجال التسليم المتوقعة،\n- شروط الضمان وخدمة ما بعد البيع.\n\nنشكركم مسبقًا على تعاونكم، ونبقى في انتظار ردكم.\n\nمع خالص التحية،' },
    fr: { to: ['Leila Amrani', 'Responsable commerciale', 'Atlas Équipements Industriels', 'l.amrani@atlas-equip.dz'],
      subject: 'Demande d’informations techniques — moteurs électriques 75 kW',
      points: 'Fiche technique, rendement énergétique, délais de livraison et garantie des moteurs 75 kW.',
      body: "Madame Amrani,\n\nDans le cadre du renouvellement d'une partie des moteurs de notre ligne de broyage, nous souhaiterions recevoir des informations techniques sur les moteurs de 75 kW que vous proposez, notamment :\n- la fiche technique et la classe de rendement (IE3 ou IE4) ;\n- les délais de livraison prévus ;\n- les conditions de garantie et de service après-vente.\n\nNous vous remercions par avance de votre retour.\n\nCordialement," },
    en: { to: ['Leila Amrani', 'Sales Manager', 'Atlas Industrial Equipment', 'l.amrani@atlas-equip.dz'],
      subject: 'Request for technical information — 75 kW electric motors',
      points: 'Datasheet, energy efficiency class, delivery times and warranty for the 75 kW motors.',
      body: 'Dear Ms Amrani,\n\nWe are renewing part of the motors on our grinding line and would like to receive technical information on the 75 kW motors you offer, in particular:\n- the datasheet and efficiency class (IE3 or IE4);\n- the expected delivery times;\n- the warranty and after-sales service terms.\n\nThank you in advance for your help. I look forward to hearing from you.\n\nBest regards,' },
  },
  quote: {
    ar: { to: ['كريم بن عيسى', 'المدير التجاري', 'مؤسسة النور للمحامل والقطع', 'commercial@nour-pieces.dz'],
      subject: 'طلب عرض سعر لقطع غيار — طلبية الربع الرابع',
      points: '4 محامل SKF 6316، 6 أحزمة SPC 4000، قاطعا دارة 250 أمبير. نريد السعر والآجال وشروط الدفع قبل 15 أكتوبر.',
      body: 'السيد كريم بن عيسى المحترم،\n\nتحية طيبة وبعد،\n\nيرجى التكرم بموافاتنا بعرض سعر مفصل للقطع التالية:\n- 4 محامل كروية SKF 6316-C3،\n- 6 أحزمة نقل SPC 4000،\n- قاطعا دارة 250 أمبير.\n\nنرجو أن يتضمن العرض الأسعار دون رسوم ومع الرسوم، آجال التسليم، وشروط الدفع، وذلك في أجل أقصاه 15 أكتوبر 2026.\n\nوتقبلوا منا فائق الاحترام،' },
    fr: { to: ['Karim Benaissa', 'Directeur commercial', 'Ennour Roulements & Pièces', 'commercial@nour-pieces.dz'],
      subject: 'Demande de devis — pièces de rechange T4',
      points: '4 roulements SKF 6316, 6 courroies SPC 4000, 2 disjoncteurs 250 A. Prix, délais, conditions de paiement avant le 15 octobre.',
      body: "Monsieur Benaissa,\n\nNous vous prions de bien vouloir nous adresser un devis détaillé pour les pièces suivantes :\n- 4 roulements à billes SKF 6316-C3 ;\n- 6 courroies de transmission SPC 4000 ;\n- 2 disjoncteurs 250 A.\n\nMerci d'indiquer les prix HT et TTC, les délais de livraison et les conditions de paiement, au plus tard le 15 octobre 2026.\n\nVeuillez agréer nos salutations distinguées," },
    en: { to: ['Karim Benaissa', 'Sales Director', 'Ennour Bearings & Parts', 'commercial@nour-pieces.dz'],
      subject: 'Quote request — Q4 spare parts',
      points: '4 SKF 6316 bearings, 6 SPC 4000 belts, 2 circuit breakers 250 A. Prices, lead times and payment terms by 15 October.',
      body: 'Dear Mr Benaissa,\n\nCould you please send us a detailed quotation for the following parts:\n- 4 SKF 6316-C3 ball bearings;\n- 6 SPC 4000 drive belts;\n- 2 circuit breakers, 250 A.\n\nPlease include prices with and without tax, delivery lead times and payment terms, by 15 October 2026 at the latest.\n\nKind regards,' },
  },
  meeting: {
    ar: { to: ['نادية حمدي', 'مديرة الإنتاج', 'مصنع الإسمنت — بشار', 'n.hamdi@ciment.dz'],
      subject: 'طلب اجتماع لتنسيق التوقف السنوي للفرن رقم 2',
      points: 'اجتماع ساعة لتنسيق التوقف السنوي للفرن 2. اقتراح: الثلاثاء 13 أو الأربعاء 14 أكتوبر صباحًا.',
      body: 'السيدة نادية حمدي المحترمة،\n\nتحية طيبة وبعد،\n\nتحضيرًا للتوقف السنوي للفرن رقم 2، أقترح عقد اجتماع تنسيقي لمدة ساعة واحدة لضبط برنامج الأشغال وتوزيع الفرق وتحديد الأولويات.\n\nأقترح أحد الموعدين التاليين:\n- الثلاثاء 13 أكتوبر على الساعة 9:00،\n- الأربعاء 14 أكتوبر على الساعة 10:00.\n\nيُرجى إعلامي بالموعد الأنسب لكم.\n\nمع خالص التحية،' },
    fr: { to: ['Nadia Hamdi', 'Directrice de production', 'Cimenterie de Béchar', 'n.hamdi@ciment.dz'],
      subject: "Demande de réunion — arrêt annuel du four n° 2",
      points: "Réunion d'une heure pour coordonner l'arrêt annuel du four 2. Mardi 13 ou mercredi 14 octobre au matin.",
      body: "Madame Hamdi,\n\nEn vue de l'arrêt annuel du four n° 2, je vous propose une réunion de coordination d'une heure afin d'arrêter le planning des travaux, la répartition des équipes et les priorités.\n\nDeux créneaux possibles :\n- mardi 13 octobre à 9 h ;\n- mercredi 14 octobre à 10 h.\n\nMerci de m'indiquer celui qui vous convient le mieux.\n\nBien cordialement," },
    en: { to: ['Nadia Hamdi', 'Production Director', 'Béchar Cement Plant', 'n.hamdi@ciment.dz'],
      subject: 'Meeting request — annual shutdown of kiln No. 2',
      points: 'One-hour meeting to coordinate the kiln 2 annual shutdown. Tuesday 13 or Wednesday 14 October, morning.',
      body: 'Dear Ms Hamdi,\n\nAhead of the annual shutdown of kiln No. 2, I would like to suggest a one-hour coordination meeting to agree on the work schedule, team allocation and priorities.\n\nTwo possible slots:\n- Tuesday 13 October at 9:00;\n- Wednesday 14 October at 10:00.\n\nPlease let me know which one suits you best.\n\nBest regards,' },
  },
  followup: {
    ar: { to: ['يوسف بلقاسم', 'مسؤول الطلبيات', 'مؤسسة الأطلس للتجهيزات الصناعية', 'y.belkacem@atlas-equip.dz'],
      subject: 'متابعة: الطلبية رقم BC-2026-118',
      points: 'لم نستلم الطلبية BC-2026-118 المقررة في 25 سبتمبر. نريد تاريخ التسليم الجديد بسرعة لأن التوقف قريب.',
      body: 'السيد يوسف بلقاسم المحترم،\n\nتحية طيبة وبعد،\n\nأعود إليكم بخصوص طلبية الشراء رقم BC-2026-118، التي كان من المقرر تسليمها يوم 25 سبتمبر 2026، ولم نستلمها إلى غاية اليوم.\n\nونظرًا لقرب موعد التوقف المبرمج للصيانة، نرجو منكم تأكيد تاريخ التسليم الجديد في أقرب الآجال، وإعلامنا بأي صعوبة قد تؤخر الإرسال.\n\nشكرًا على تفهمكم وتعاونكم.\n\nمع خالص التحية،' },
    fr: { to: ['Youcef Belkacem', 'Responsable des commandes', 'Atlas Équipements Industriels', 'y.belkacem@atlas-equip.dz'],
      subject: 'Relance : commande n° BC-2026-118',
      points: "Commande BC-2026-118 prévue le 25 septembre, non reçue. Besoin d'une nouvelle date rapidement, arrêt proche.",
      body: "Monsieur Belkacem,\n\nJe reviens vers vous au sujet de la commande n° BC-2026-118, dont la livraison était prévue le 25 septembre 2026 et que nous n'avons pas encore reçue.\n\nNotre arrêt de maintenance approchant, je vous remercie de bien vouloir nous confirmer rapidement la nouvelle date de livraison et de nous signaler toute difficulté éventuelle.\n\nMerci pour votre réactivité.\n\nCordialement," },
    en: { to: ['Youcef Belkacem', 'Order Manager', 'Atlas Industrial Equipment', 'y.belkacem@atlas-equip.dz'],
      subject: 'Follow-up: purchase order BC-2026-118',
      points: 'Order BC-2026-118 due on 25 September not received. Need a new date quickly, shutdown is close.',
      body: 'Dear Mr Belkacem,\n\nI am following up on purchase order BC-2026-118, which was due for delivery on 25 September 2026 and which we have not yet received.\n\nAs our maintenance shutdown is approaching, could you please confirm the new delivery date as soon as possible and let us know of any difficulty that might delay shipment?\n\nThank you for your help.\n\nBest regards,' },
  },
  reply: {
    ar: { to: ['مراد قاسمي', 'مسير', 'شركة البناء الحديث', 'm.kacimi@binaa.dz'],
      subject: 'رد: استفسار حول آجال تسليم الإسمنت CEM II',
      points: 'شكرًا على الطلب. 200 طن متوفرة. التسليم خلال 5 أيام عمل بعد تأكيد الطلبية. العرض صالح 30 يومًا.',
      body: 'السيد مراد قاسمي المحترم،\n\nتحية طيبة وبعد،\n\nنشكركم على ثقتكم واهتمامكم بمنتجاتنا. يسعدنا إعلامكم بأن الكمية المطلوبة (200 طن من الإسمنت CEM II) متوفرة حاليًا، ويمكن تسليمها خلال 5 أيام عمل من تاريخ تأكيد الطلبية.\n\nتجدون مرفقًا عرض السعر، وهو صالح لمدة 30 يومًا. ولأي استفسار إضافي، فريقنا التجاري في خدمتكم.\n\nمع خالص التحية،' },
    fr: { to: ['Mourad Kacimi', 'Gérant', 'Binaa Moderne', 'm.kacimi@binaa.dz'],
      subject: 'Re : délais de livraison du ciment CEM II',
      points: 'Merci pour la demande. 200 t disponibles. Livraison sous 5 jours ouvrés après confirmation. Offre valable 30 jours.',
      body: "Monsieur Kacimi,\n\nNous vous remercions de votre confiance. Nous avons le plaisir de vous informer que la quantité demandée (200 tonnes de ciment CEM II) est disponible et peut être livrée sous 5 jours ouvrés à compter de la confirmation de commande.\n\nVous trouverez ci-joint notre offre de prix, valable 30 jours. Notre équipe commerciale reste à votre disposition pour toute question.\n\nCordialement," },
    en: { to: ['Mourad Kacimi', 'Managing Director', 'Binaa Moderne', 'm.kacimi@binaa.dz'],
      subject: 'Re: delivery times for CEM II cement',
      points: 'Thanks for the enquiry. 200 t available. Delivery within 5 working days after confirmation. Offer valid 30 days.',
      body: 'Dear Mr Kacimi,\n\nThank you for your interest in our products. I am pleased to confirm that the quantity you requested (200 tonnes of CEM II cement) is available and can be delivered within 5 working days of your order confirmation.\n\nPlease find our price offer attached; it is valid for 30 days. Our sales team remains at your disposal for any further questions.\n\nKind regards,' },
  },
  sendfile: {
    ar: { to: ['نادية حمدي', 'مديرة الإنتاج', 'مصنع الإسمنت — بشار', 'n.hamdi@ciment.dz'],
      subject: 'إرسال تقرير الصيانة الشهري — سبتمبر 2026',
      points: 'أرسل تقرير صيانة سبتمبر بصيغة PDF. أهم النقاط: توفر المعدات 96%، 3 أعطال كبرى عولجت. مستعد لشرحه.',
      body: 'السيدة نادية حمدي المحترمة،\n\nتحية طيبة وبعد،\n\nتجدون في المرفق تقرير الصيانة الشهري لشهر سبتمبر 2026 بصيغة PDF.\n\nأبرز ما جاء فيه:\n- نسبة توفر المعدات: 96%،\n- معالجة 3 أعطال كبرى على خط الطحن،\n- برنامج الصيانة الوقائية لشهر أكتوبر.\n\nأنا مستعد لتقديم أي توضيح أو عرض النتائج في الاجتماع القادم.\n\nمع خالص التحية،' },
    fr: { to: ['Nadia Hamdi', 'Directrice de production', 'Cimenterie de Béchar', 'n.hamdi@ciment.dz'],
      subject: 'Envoi du rapport de maintenance — septembre 2026',
      points: 'Rapport de maintenance de septembre en PDF. Disponibilité 96 %, 3 pannes majeures traitées. Disponible pour en parler.',
      body: "Madame Hamdi,\n\nVeuillez trouver ci-joint le rapport de maintenance du mois de septembre 2026 au format PDF.\n\nPoints principaux :\n- disponibilité des équipements : 96 % ;\n- 3 pannes majeures traitées sur la ligne de broyage ;\n- programme de maintenance préventive d'octobre.\n\nJe reste à votre disposition pour tout complément ou pour présenter les résultats lors de la prochaine réunion.\n\nBien cordialement," },
    en: { to: ['Nadia Hamdi', 'Production Director', 'Béchar Cement Plant', 'n.hamdi@ciment.dz'],
      subject: 'Maintenance report — September 2026',
      points: 'Send the September maintenance report as PDF. Availability 96%, 3 major failures fixed. Happy to present it.',
      body: "Dear Ms Hamdi,\n\nPlease find attached the maintenance report for September 2026 in PDF format.\n\nKey points:\n- equipment availability: 96%;\n- 3 major failures resolved on the grinding line;\n- October's preventive maintenance plan.\n\nI would be happy to clarify any point or present the results at the next meeting.\n\nBest regards," },
  },
  complaint: {
    ar: { to: ['', 'مصلحة خدمة العملاء', 'مؤسسة النقل السريع', 'service.clients@transport-rapide.dz'],
      subject: 'شكوى بخصوص تأخر وتلف شحنة قطع الغيار',
      points: 'الشحنة رقم TR-55821 وصلت متأخرة 6 أيام وصندوقان تالفان. نريد تحقيقًا وتعويضًا وحلًا خلال أسبوع.',
      body: 'السادة مصلحة خدمة العملاء المحترمون،\n\nتحية طيبة وبعد،\n\nنود إعلامكم بأن الشحنة رقم TR-55821 وصلت إلى مصنعنا متأخرة بستة أيام عن الموعد المتفق عليه، كما وُجد صندوقان منها تالفين، مما تسبب في تأجيل أشغال صيانة مبرمجة.\n\nلذا نطلب منكم فتح تحقيق في الأمر، وتعويض القطع التالفة، وموافاتنا بحل في أجل أقصاه أسبوع. تجدون في المرفق صور الطرود ومحضر الاستلام.\n\nوتقبلوا فائق الاحترام،' },
    fr: { to: ['', 'Service clients', 'Transport Rapide', 'service.clients@transport-rapide.dz'],
      subject: 'Réclamation — retard et avarie de la livraison TR-55821',
      points: 'Envoi TR-55821 arrivé avec 6 jours de retard, 2 caisses endommagées. Demande enquête, remplacement, réponse sous une semaine.',
      body: "Madame, Monsieur,\n\nNous vous informons que l'envoi n° TR-55821 est arrivé dans notre usine avec six jours de retard sur la date convenue, et que deux caisses ont été livrées endommagées, ce qui a retardé des travaux de maintenance programmés.\n\nNous vous demandons d'ouvrir une enquête, de remplacer les pièces abîmées et de nous proposer une solution sous huit jours. Vous trouverez ci-joint les photos des colis et le procès-verbal de réception.\n\nVeuillez agréer nos salutations distinguées," },
    en: { to: ['', 'Customer Service', 'Rapid Transport Co.', 'service.clients@transport-rapide.dz'],
      subject: 'Complaint — late and damaged shipment TR-55821',
      points: 'Shipment TR-55821 arrived 6 days late, 2 crates damaged. Ask for investigation, replacement and an answer within a week.',
      body: 'Dear Customer Service team,\n\nShipment No. TR-55821 reached our plant six days later than agreed, and two crates were delivered damaged. This delayed scheduled maintenance work.\n\nWe therefore ask you to investigate the matter, replace the damaged parts and propose a solution within one week. Photos of the parcels and the delivery report are attached.\n\nYours faithfully,' },
  },
  apology: {
    ar: { to: ['مراد قاسمي', 'مسير', 'شركة البناء الحديث', 'm.kacimi@binaa.dz'],
      subject: 'اعتذار عن تأخر تسليم طلبيتكم',
      points: 'نعتذر عن تأخر الطلبية يومين بسبب عطل في خط التعبئة. العطل أُصلح والتسليم غدًا الخميس. خصم 3% تعويضًا.',
      body: 'السيد مراد قاسمي المحترم،\n\nتحية طيبة وبعد،\n\nنقدم لكم خالص اعتذارنا عن تأخر تسليم طلبيتكم بيومين، والذي يعود إلى عطل طارئ في خط التعبئة.\n\nنحيطكم علمًا بأن العطل قد أُصلح بالكامل، وأن التسليم سيتم غدًا الخميس صباحًا. وتقديرًا لتفهمكم، يسعدنا منحكم خصمًا بنسبة 3% على هذه الطلبية.\n\nنشكركم على صبركم وثقتكم المتجددة.\n\nمع خالص التحية،' },
    fr: { to: ['Mourad Kacimi', 'Gérant', 'Binaa Moderne', 'm.kacimi@binaa.dz'],
      subject: 'Toutes nos excuses pour le retard de votre commande',
      points: "Retard de 2 jours dû à une panne de la ligne d'ensachage. Panne réparée, livraison demain jeudi. Remise de 3 %.",
      body: "Monsieur Kacimi,\n\nNous vous prions de bien vouloir excuser le retard de deux jours dans la livraison de votre commande, dû à une panne imprévue de notre ligne d'ensachage.\n\nLa panne est désormais réparée et la livraison aura lieu demain jeudi matin. Pour vous remercier de votre compréhension, nous avons le plaisir de vous accorder une remise de 3 % sur cette commande.\n\nMerci pour votre patience et votre confiance.\n\nCordialement," },
    en: { to: ['Mourad Kacimi', 'Managing Director', 'Binaa Moderne', 'm.kacimi@binaa.dz'],
      subject: 'Our apologies for the delayed delivery',
      points: 'Sorry for the 2-day delay caused by a packing line failure. Fixed, delivery tomorrow Thursday. 3% discount.',
      body: 'Dear Mr Kacimi,\n\nPlease accept our sincere apologies for the two-day delay in delivering your order, caused by an unexpected failure on our packing line.\n\nThe fault has now been fully repaired and your delivery will arrive tomorrow, Thursday morning. To thank you for your understanding, we are pleased to offer you a 3% discount on this order.\n\nThank you for your patience and continued trust.\n\nKind regards,' },
  },
  thanks: {
    ar: { to: ['ياسين عمراني', 'رئيس فريق الصيانة الليلية', 'مصنع الإسمنت — بشار', 'y.amrani@ciment.dz'],
      subject: 'شكر وتقدير لفريق الصيانة',
      points: 'شكرًا للفريق على التدخل ليلة السبت لإصلاح المطحنة رقم 3. أعيد التشغيل في 4 ساعات بدل يومين.',
      body: 'السيد ياسين عمراني المحترم،\n\nتحية طيبة وبعد،\n\nأتوجه إليكم وإلى كامل فريق الصيانة الليلية بخالص الشكر والتقدير على تدخلكم السريع ليلة السبت لإصلاح عطل المطحنة رقم 3.\n\nلقد مكّن تفانيكم واحترافيتكم من إعادة التشغيل في أقل من أربع ساعات، بدل يومين كانا متوقعين، وهو ما جنّب المصنع خسائر معتبرة في الإنتاج.\n\nبارك الله في جهودكم.\n\nمع خالص التقدير،' },
    fr: { to: ['Yacine Amrani', "Chef de l'équipe de maintenance de nuit", 'Cimenterie de Béchar', 'y.amrani@ciment.dz'],
      subject: "Merci à l'équipe de maintenance",
      points: "Merci à l'équipe pour l'intervention de samedi soir sur le broyeur 3. Redémarrage en 4 h au lieu de 2 jours.",
      body: "Monsieur Amrani,\n\nJe tiens à vous adresser, ainsi qu'à toute l'équipe de maintenance de nuit, mes sincères remerciements pour votre intervention rapide samedi soir sur le broyeur n° 3.\n\nVotre engagement et votre professionnalisme ont permis de redémarrer en moins de quatre heures au lieu des deux jours prévus, évitant à l'usine d'importantes pertes de production.\n\nBravo et merci encore.\n\nBien cordialement," },
    en: { to: ['Yacine Amrani', 'Night Maintenance Team Leader', 'Béchar Cement Plant', 'y.amrani@ciment.dz'],
      subject: 'Thank you to the maintenance team',
      points: 'Thank the team for the Saturday night repair on mill 3. Restarted in 4 hours instead of 2 days.',
      body: 'Dear Mr Amrani,\n\nI would like to thank you and the whole night maintenance team for your quick response on Saturday night to repair mill No. 3.\n\nYour commitment and professionalism allowed us to restart in less than four hours instead of the expected two days, saving the plant significant production losses.\n\nWell done, and thank you again.\n\nWarm regards,' },
  },
  leave: {
    ar: { to: ['', 'مدير الموارد البشرية', 'مصنع الإسمنت — بشار', 'rh@ciment.dz'],
      subject: 'طلب عطلة سنوية من 10 إلى 24 نوفمبر 2026',
      points: 'عطلة سنوية 15 يومًا من 10 إلى 24 نوفمبر. الملفات الجارية سُلّمت للزميل كريم بن عيسى.',
      body: 'السيد مدير الموارد البشرية المحترم،\n\nتحية طيبة وبعد،\n\nيشرفني أن أتقدم إليكم بطلب الاستفادة من عطلتي السنوية لمدة 15 يومًا، من 10 إلى 24 نوفمبر 2026.\n\nوقد حرصت على تسليم الملفات الجارية إلى زميلي كريم بن عيسى، الذي سيتولى المتابعة خلال فترة غيابي، ضمانًا لسير العمل بشكل عادي.\n\nوفي انتظار موافقتكم، تقبلوا مني فائق الاحترام والتقدير.' },
    fr: { to: ['', 'Directeur des ressources humaines', 'Cimenterie de Béchar', 'rh@ciment.dz'],
      subject: 'Demande de congé annuel du 10 au 24 novembre 2026',
      points: 'Congé annuel de 15 jours du 10 au 24 novembre. Dossiers en cours transmis à Karim Benaissa.',
      body: "Monsieur le Directeur,\n\nJ'ai l'honneur de solliciter mon congé annuel pour une durée de 15 jours, du 10 au 24 novembre 2026.\n\nJ'ai transmis les dossiers en cours à mon collègue Karim Benaissa, qui en assurera le suivi pendant mon absence afin de garantir la continuité du service.\n\nDans l'attente de votre accord, je vous prie d'agréer, Monsieur le Directeur, l'expression de mes salutations distinguées." },
    en: { to: ['', 'HR Manager', 'Béchar Cement Plant', 'rh@ciment.dz'],
      subject: 'Annual leave request — 10 to 24 November 2026',
      points: '15 days of annual leave from 10 to 24 November. Ongoing files handed over to Karim Benaissa.',
      body: 'Dear HR Manager,\n\nI would like to request 15 days of annual leave, from 10 to 24 November 2026.\n\nI have handed over my ongoing files to my colleague Karim Benaissa, who will follow them up during my absence to ensure continuity of work.\n\nThank you for considering my request.\n\nKind regards,' },
  },
  application: {
    ar: { to: ['', 'مصلحة التوظيف', 'مجمع لافارج هولسيم الجزائر', 'recrutement@lafarge.dz'],
      subject: 'ترشح لمنصب مهندس صيانة كهربائية — المرجع ING-ELEC-07',
      points: 'ترشح لمنصب مهندس صيانة كهربائية. 8 سنوات خبرة في مصانع الإسمنت، دكتوراه في الإلكترونيك. السيرة الذاتية مرفقة.',
      body: 'السادة مصلحة التوظيف المحترمون،\n\nتحية طيبة وبعد،\n\nيسعدني أن أتقدم إليكم بترشحي لمنصب مهندس صيانة كهربائية المعلن عنه تحت المرجع ING-ELEC-07.\n\nأتمتع بخبرة ثماني سنوات في صيانة المنشآت الكهربائية بمصانع الإسمنت، وأحمل شهادة دكتوراه في الإلكترونيك الطاقوية، مع خبرة في تحسين الكفاءة الطاقوية وتسيير فرق الصيانة.\n\nتجدون في المرفق سيرتي الذاتية، وأنا مستعد لإجراء مقابلة في الموعد الذي يناسبكم.\n\nمع خالص التحية،' },
    fr: { to: ['', 'Service recrutement', 'Lafarge Holcim Algérie', 'recrutement@lafarge.dz'],
      subject: "Candidature — Ingénieur maintenance électrique (réf. ING-ELEC-07)",
      points: 'Candidature ingénieur maintenance électrique. 8 ans en cimenterie, doctorat en électronique. CV joint.',
      body: "Madame, Monsieur,\n\nJe me permets de vous adresser ma candidature au poste d'ingénieur maintenance électrique publié sous la référence ING-ELEC-07.\n\nFort de huit années d'expérience dans la maintenance des installations électriques en cimenterie et titulaire d'un doctorat en électronique de puissance, j'ai notamment mené des projets d'efficacité énergétique et encadré des équipes de maintenance.\n\nVous trouverez mon CV en pièce jointe. Je me tiens à votre disposition pour un entretien.\n\nCordialement," },
    en: { to: ['', 'Recruitment Team', 'Lafarge Holcim Algeria', 'recrutement@lafarge.dz'],
      subject: 'Application — Electrical Maintenance Engineer (ref. ING-ELEC-07)',
      points: 'Application for electrical maintenance engineer. 8 years in cement plants, PhD in electronics. CV attached.',
      body: 'Dear Hiring Team,\n\nI am writing to apply for the Electrical Maintenance Engineer position advertised under reference ING-ELEC-07.\n\nI have eight years of experience maintaining electrical installations in cement plants and hold a PhD in power electronics. I have led energy-efficiency projects and managed maintenance teams.\n\nPlease find my CV attached. I would welcome the opportunity to discuss my application at your convenience.\n\nKind regards,' },
  },
  intro: {
    ar: { to: ['د. ليلى عمراني', 'أستاذة باحثة', 'المدرسة الوطنية المتعددة التقنيات', 'l.amrani@enp.edu.dz'],
      subject: 'تعارف واقتراح تعاون في مجال النجاعة الطاقوية',
      points: 'أقدم نفسي: رئيس مكتب الدراسات بمصنع الإسمنت. قرأت بحثك عن المحركات عالية الكفاءة. أقترح تعاونًا وتربصات للطلبة.',
      body: 'الدكتورة ليلى عمراني المحترمة،\n\nتحية طيبة وبعد،\n\nاسمحي لي أن أقدم نفسي: سفيان مرابطي، رئيس مكتب الدراسات والصيانة بمصنع الإسمنت ببشار. اطلعت باهتمام على بحثكم الأخير حول المحركات عالية الكفاءة، وأرى فيه حلولًا قابلة للتطبيق في منشآتنا.\n\nأود أن أقترح عليكم تعاونًا يشمل دراسة حالة ميدانية واستقبال طلبة للتربص بمصنعنا. يسعدني ترتيب اتصال قصير لمناقشة الفكرة في الوقت الذي يناسبكم.\n\nمع خالص التحية،' },
    fr: { to: ['Dr Leila Amrani', 'Enseignante-chercheuse', 'École Nationale Polytechnique', 'l.amrani@enp.edu.dz'],
      subject: "Présentation et proposition de collaboration en efficacité énergétique",
      points: "Me présenter : chef du bureau d'études de la cimenterie. J'ai lu votre article sur les moteurs à haut rendement. Proposer une collaboration et des stages.",
      body: "Madame Amrani,\n\nPermettez-moi de me présenter : Sofiane Merabti, chef du bureau d'études et maintenance de la cimenterie de Béchar. J'ai lu avec intérêt votre récent article sur les moteurs à haut rendement, qui propose des solutions applicables à nos installations.\n\nJe souhaiterais vous proposer une collaboration comprenant une étude de cas sur site et l'accueil d'étudiants en stage. Je serais ravi d'en discuter lors d'un court échange, à votre convenance.\n\nBien cordialement," },
    en: { to: ['Dr Leila Amrani', 'Researcher and Lecturer', 'National Polytechnic School', 'l.amrani@enp.edu.dz'],
      subject: 'Introduction and proposed collaboration on energy efficiency',
      points: 'Introduce myself: head of engineering at the cement plant. Read your paper on high-efficiency motors. Propose collaboration and student internships.',
      body: 'Dear Dr Amrani,\n\nAllow me to introduce myself: I am Sofiane Merabti, Head of Engineering and Maintenance at the Béchar cement plant. I read your recent paper on high-efficiency motors with great interest, as it offers solutions that could apply to our installations.\n\nI would like to propose a collaboration including an on-site case study and internships for your students. I would be glad to arrange a short call at your convenience.\n\nBest regards,' },
  },
  free: {
    ar: { to: ['فريق الإنتاج', '', 'مصنع الإسمنت — بشار', 'production@ciment.dz'],
      subject: 'إعلام: انقطاع الكهرباء المبرمج يوم السبت',
      points: 'انقطاع كهرباء مبرمج السبت 17 أكتوبر من 6 إلى 10 صباحًا لصيانة المحول الرئيسي. إيقاف الخطوط قبلها بنصف ساعة.',
      body: 'إلى كافة أعضاء فريق الإنتاج،\n\nتحية طيبة وبعد،\n\nنعلمكم بأن انقطاعًا مبرمجًا للتيار الكهربائي سيتم يوم السبت 17 أكتوبر 2026 من الساعة 6:00 إلى 10:00 صباحًا، وذلك لإجراء الصيانة الدورية للمحول الرئيسي.\n\nيُرجى إيقاف خطوط الإنتاج بصفة آمنة قبل الساعة 5:30، والالتزام بتعليمات السلامة المعمول بها.\n\nشكرًا على تعاونكم.\n\nمع خالص التحية،' },
    fr: { to: ['Équipe de production', '', 'Cimenterie de Béchar', 'production@ciment.dz'],
      subject: 'Information : coupure électrique programmée samedi',
      points: 'Coupure programmée samedi 17 octobre de 6 h à 10 h pour la maintenance du transformateur principal. Arrêter les lignes 30 min avant.',
      body: "À toute l'équipe de production,\n\nUne coupure d'électricité programmée aura lieu le samedi 17 octobre 2026 de 6 h à 10 h, pour la maintenance périodique du transformateur principal.\n\nMerci d'arrêter les lignes de production en toute sécurité avant 5 h 30 et de respecter les consignes de sécurité en vigueur.\n\nMerci de votre collaboration.\n\nCordialement," },
    en: { to: ['Production team', '', 'Béchar Cement Plant', 'production@ciment.dz'],
      subject: 'Notice: scheduled power outage on Saturday',
      points: 'Scheduled outage Saturday 17 October 6–10 am for main transformer maintenance. Stop the lines 30 minutes before.',
      body: 'To all members of the production team,\n\nA scheduled power outage will take place on Saturday 17 October 2026 from 6:00 to 10:00 am for the periodic maintenance of the main transformer.\n\nPlease shut down the production lines safely before 5:30 am and follow the applicable safety instructions.\n\nThank you for your cooperation.\n\nBest regards,' },
  },
};
