// ============================================================
// data.js — Word keyboard shortcuts lesson content
// ============================================================

const CATS = [
  { id: 'editing',      name: { ar: 'التحرير', en: 'Editing' } },
  { id: 'formatting',   name: { ar: 'التنسيق', en: 'Formatting' } },
  { id: 'documents',    name: { ar: 'المستندات', en: 'Documents' } },
  { id: 'navigation',   name: { ar: 'التنقل', en: 'Navigation' } },
  { id: 'tables',       name: { ar: 'الجداول', en: 'Tables' } },
  { id: 'objects',      name: { ar: 'العناصر', en: 'Objects' } },
  { id: 'view',         name: { ar: 'العرض والوصول', en: 'View & Access' } },
  { id: 'review',       name: { ar: 'المراجعة والتدقيق', en: 'Review & Proofing' } },
];

const SC = [
  /* ---------------- EDITING ---------------- */
  { cat: 'editing', keys: ['Ctrl', 'C'], name: { ar: 'نسخ', en: 'Copy' }, desc: { ar: 'نسخ النص أو العنصر المحدد', en: 'Copy the selected text or object' } },
  { cat: 'editing', keys: ['Ctrl', 'V'], name: { ar: 'لصق', en: 'Paste' }, desc: { ar: 'لصق المحتوى المنسوخ من الحافظة', en: 'Paste content from the clipboard' } },
  { cat: 'editing', keys: ['Ctrl', 'X'], name: { ar: 'قص', en: 'Cut' }, desc: { ar: 'قص العنصر المحدد ونقله للحافظة', en: 'Cut the selection and move it to the clipboard' } },
  { cat: 'editing', keys: ['Ctrl', 'Z'], name: { ar: 'تراجع', en: 'Undo' }, desc: { ar: 'التراجع عن آخر إجراء قمت به', en: 'Undo your last action' } },
  { cat: 'editing', keys: ['Ctrl', 'Y'], name: { ar: 'إعادة', en: 'Redo' }, desc: { ar: 'إعادة تنفيذ الإجراء الذي تراجعت عنه', en: 'Redo an action you just undid' } },
  { cat: 'editing', keys: ['F4'], name: { ar: 'تكرار الإجراء', en: 'Repeat' }, desc: { ar: 'تكرار آخر إجراء قمت به', en: 'Repeat your last action' } },
  { cat: 'editing', keys: ['Ctrl', 'F'], name: { ar: 'بحث', en: 'Find' }, desc: { ar: 'البحث عن كلمة أو عبارة في المستند', en: 'Find a word or phrase in the document' } },
  { cat: 'editing', keys: ['Ctrl', 'H'], name: { ar: 'استبدال', en: 'Replace' }, desc: { ar: 'استبدال كلمة بأخرى في كل المستند', en: 'Replace one word with another across the document' } },
  { cat: 'editing', keys: ['Ctrl', 'A'], name: { ar: 'تحديد الكل', en: 'Select All' }, desc: { ar: 'تحديد كامل محتوى المستند', en: 'Select the entire document content' } },
  { cat: 'editing', keys: ['Ctrl', 'G'], name: { ar: 'الانتقال إلى', en: 'Go To' }, desc: { ar: 'الانتقال مباشرة إلى صفحة أو سطر محدد', en: 'Jump directly to a specific page or line' } },
  { cat: 'editing', keys: ['Ctrl', 'Backspace'], name: { ar: 'حذف كلمة سابقة', en: 'Delete Word Back' }, desc: { ar: 'حذف الكلمة السابقة كاملة دفعة واحدة', en: 'Delete the entire previous word at once' } },
  { cat: 'editing', keys: ['Ctrl', 'Delete'], name: { ar: 'حذف كلمة تالية', en: 'Delete Word Forward' }, desc: { ar: 'حذف الكلمة التالية كاملة دفعة واحدة', en: 'Delete the entire next word at once' } },
  { cat: 'editing', keys: ['Ctrl', 'Alt', 'V'], name: { ar: 'لصق خاص', en: 'Paste Special' }, desc: { ar: 'فتح خيارات لصق متقدمة', en: 'Open advanced paste options' } },
  { cat: 'editing', keys: ['Ctrl', 'Shift', '→'], name: { ar: 'تحديد كلمة', en: 'Select Word' }, desc: { ar: 'تمديد التحديد إلى نهاية الكلمة التالية', en: 'Extend the selection to the end of the next word' } },
  { cat: 'editing', keys: ['Shift', 'Home'], name: { ar: 'تحديد لبداية السطر', en: 'Select to Line Start' }, desc: { ar: 'تحديد النص من موضع المؤشر لبداية السطر', en: 'Select from the cursor to the start of the line' } },
  { cat: 'editing', keys: ['Shift', 'End'], name: { ar: 'تحديد لنهاية السطر', en: 'Select to Line End' }, desc: { ar: 'تحديد النص من موضع المؤشر لنهاية السطر', en: 'Select from the cursor to the end of the line' } },
  { cat: 'editing', keys: ['Ctrl', 'Shift', '↓'], name: { ar: 'تحديد حتى نهاية الفقرة', en: 'Select to Paragraph End' }, desc: { ar: 'تمديد التحديد حتى نهاية الفقرة الحالية', en: 'Extend the selection to the end of the current paragraph' } },
  { cat: 'editing', keys: ['F3'], name: { ar: 'إدراج نص تلقائي', en: 'Insert AutoText' }, desc: { ar: 'إكمال أو إدراج عنصر نص تلقائي محفوظ', en: 'Complete or insert a saved AutoText entry' } },

  /* ---------------- FORMATTING ---------------- */
  { cat: 'formatting', keys: ['Ctrl', 'B'], name: { ar: 'غامق', en: 'Bold' }, desc: { ar: 'جعل النص المحدد بخط غامق', en: 'Make the selected text bold' } },
  { cat: 'formatting', keys: ['Ctrl', 'I'], name: { ar: 'مائل', en: 'Italic' }, desc: { ar: 'جعل النص المحدد بخط مائل', en: 'Make the selected text italic' } },
  { cat: 'formatting', keys: ['Ctrl', 'U'], name: { ar: 'تسطير', en: 'Underline' }, desc: { ar: 'وضع خط تحت النص المحدد', en: 'Underline the selected text' } },
  { cat: 'formatting', keys: ['Ctrl', 'Shift', 'D'], name: { ar: 'تسطير مزدوج', en: 'Double Underline' }, desc: { ar: 'وضع خطين تحت النص المحدد', en: 'Apply a double underline to the selection' } },
  { cat: 'formatting', keys: ['Ctrl', 'Shift', 'W'], name: { ar: 'تسطير الكلمات فقط', en: 'Word Underline' }, desc: { ar: 'تسطير الكلمات دون تسطير المسافات بينها', en: 'Underline words but not the spaces between them' } },
  { cat: 'formatting', keys: ['Ctrl', 'E'], name: { ar: 'توسيط', en: 'Center Align' }, desc: { ar: 'توسيط الفقرة المحددة', en: 'Center-align the selected paragraph' } },
  { cat: 'formatting', keys: ['Ctrl', 'L'], name: { ar: 'محاذاة لليسار', en: 'Align Left' }, desc: { ar: 'محاذاة الفقرة إلى اليسار', en: 'Align the paragraph to the left' } },
  { cat: 'formatting', keys: ['Ctrl', 'R'], name: { ar: 'محاذاة لليمين', en: 'Align Right' }, desc: { ar: 'محاذاة الفقرة إلى اليمين', en: 'Align the paragraph to the right' } },
  { cat: 'formatting', keys: ['Ctrl', 'J'], name: { ar: 'ضبط', en: 'Justify' }, desc: { ar: 'محاذاة الفقرة من الجانبين', en: 'Justify the paragraph on both sides' } },
  { cat: 'formatting', keys: ['Ctrl', 'Shift', '>'], name: { ar: 'تكبير حجم الخط', en: 'Increase Font Size' }, desc: { ar: 'زيادة حجم الخط للنص المحدد', en: 'Increase the font size of the selection' } },
  { cat: 'formatting', keys: ['Ctrl', 'Shift', '<'], name: { ar: 'تصغير حجم الخط', en: 'Decrease Font Size' }, desc: { ar: 'إنقاص حجم الخط للنص المحدد', en: 'Decrease the font size of the selection' } },
  { cat: 'formatting', keys: ['Ctrl', 'Space'], name: { ar: 'إزالة تنسيق الأحرف', en: 'Clear Character Formatting' }, desc: { ar: 'إزالة تنسيق الخط عن النص المحدد', en: 'Remove character formatting from the selection' } },
  { cat: 'formatting', keys: ['Ctrl', 'Q'], name: { ar: 'إزالة تنسيق الفقرة', en: 'Clear Paragraph Formatting' }, desc: { ar: 'إعادة الفقرة المحددة لتنسيقها الافتراضي', en: 'Reset the selected paragraph to its default formatting' } },
  { cat: 'formatting', keys: ['Ctrl', 'Shift', '='], name: { ar: 'رفع النص (أُس)', en: 'Superscript' }, desc: { ar: 'رفع النص المحدد كأُس فوق السطر', en: 'Raise the selection above the line as superscript' } },
  { cat: 'formatting', keys: ['Ctrl', '='], name: { ar: 'خفض النص (منخفض)', en: 'Subscript' }, desc: { ar: 'خفض النص المحدد أسفل السطر', en: 'Lower the selection below the line as subscript' } },
  { cat: 'formatting', keys: ['Ctrl', 'Shift', 'A'], name: { ar: 'أحرف كبيرة بالكامل', en: 'All Caps' }, desc: { ar: 'تحويل النص المحدد لأحرف كبيرة', en: 'Format the selection as all capital letters' } },
  { cat: 'formatting', keys: ['Ctrl', 'Shift', 'K'], name: { ar: 'أحرف كبيرة صغيرة الحجم', en: 'Small Caps' }, desc: { ar: 'تحويل النص لأحرف كبيرة بحجم صغير', en: 'Format the selection as small capital letters' } },
  { cat: 'formatting', keys: ['Shift', 'F3'], name: { ar: 'تبديل حالة الأحرف', en: 'Change Case' }, desc: { ar: 'التبديل بين حالات الأحرف (كبيرة/صغيرة)', en: 'Cycle the selection through letter cases' } },
  { cat: 'formatting', keys: ['Ctrl', '1'], name: { ar: 'تباعد سطر مفرد', en: 'Single Line Spacing' }, desc: { ar: 'ضبط تباعد الأسطر على مفرد', en: 'Set line spacing to single' } },
  { cat: 'formatting', keys: ['Ctrl', '2'], name: { ar: 'تباعد سطر مزدوج', en: 'Double Line Spacing' }, desc: { ar: 'ضبط تباعد الأسطر على مزدوج', en: 'Set line spacing to double' } },
  { cat: 'formatting', keys: ['Ctrl', '5'], name: { ar: 'تباعد سطر 1.5', en: '1.5 Line Spacing' }, desc: { ar: 'ضبط تباعد الأسطر على 1.5', en: 'Set line spacing to 1.5' } },
  { cat: 'formatting', keys: ['Ctrl', '0'], name: { ar: 'مسافة قبل الفقرة', en: 'Toggle Space Before Paragraph' }, desc: { ar: 'إضافة أو إزالة مسافة قبل الفقرة', en: 'Add or remove spacing before the paragraph' } },
  { cat: 'formatting', keys: ['Ctrl', 'T'], name: { ar: 'إزاحة معلّقة', en: 'Hanging Indent' }, desc: { ar: 'إنشاء إزاحة معلّقة للفقرة', en: 'Create a hanging indent for the paragraph' } },
  { cat: 'formatting', keys: ['Ctrl', 'Shift', 'T'], name: { ar: 'إزالة الإزاحة المعلّقة', en: 'Remove Hanging Indent' }, desc: { ar: 'التراجع عن الإزاحة المعلّقة', en: 'Remove a hanging indent' } },
  { cat: 'formatting', keys: ['Ctrl', 'M'], name: { ar: 'زيادة الإزاحة', en: 'Increase Indent' }, desc: { ar: 'زيادة إزاحة الفقرة من اليسار', en: 'Increase the paragraph indent' } },
  { cat: 'formatting', keys: ['Ctrl', 'Shift', 'M'], name: { ar: 'تقليل الإزاحة', en: 'Decrease Indent' }, desc: { ar: 'تقليل إزاحة الفقرة من اليسار', en: 'Decrease the paragraph indent' } },
  { cat: 'formatting', keys: ['Ctrl', 'Alt', '1'], name: { ar: 'عنوان 1', en: 'Heading 1' }, desc: { ar: 'تطبيق نمط العنوان الأول', en: 'Apply the Heading 1 style' } },
  { cat: 'formatting', keys: ['Ctrl', 'Alt', '2'], name: { ar: 'عنوان 2', en: 'Heading 2' }, desc: { ar: 'تطبيق نمط العنوان الثاني', en: 'Apply the Heading 2 style' } },
  { cat: 'formatting', keys: ['Ctrl', 'Alt', '3'], name: { ar: 'عنوان 3', en: 'Heading 3' }, desc: { ar: 'تطبيق نمط العنوان الثالث', en: 'Apply the Heading 3 style' } },
  { cat: 'formatting', keys: ['Ctrl', 'Shift', 'N'], name: { ar: 'النمط العادي', en: 'Normal Style' }, desc: { ar: 'تطبيق نمط النص العادي', en: 'Apply the Normal paragraph style' } },
  { cat: 'formatting', keys: ['Ctrl', 'D'], name: { ar: 'مربع حوار الخط', en: 'Font Dialog' }, desc: { ar: 'فتح مربع حوار إعدادات الخط الكاملة', en: 'Open the full Font dialog box' } },
  { cat: 'formatting', keys: ['Ctrl', 'Shift', 'C'], name: { ar: 'نسخ التنسيق', en: 'Copy Formatting' }, desc: { ar: 'نسخ تنسيق النص المحدد (فرشاة التنسيق)', en: 'Copy the formatting of the selection (Format Painter)' } },
  { cat: 'formatting', keys: ['Ctrl', 'Shift', 'V'], name: { ar: 'لصق التنسيق', en: 'Paste Formatting' }, desc: { ar: 'لصق التنسيق المنسوخ على نص آخر', en: 'Apply copied formatting to other text' } },

  /* ---------------- DOCUMENTS ---------------- */
  { cat: 'documents', keys: ['Ctrl', 'N'], name: { ar: 'مستند جديد', en: 'New Document' }, desc: { ar: 'فتح مستند جديد فارغ', en: 'Open a new blank document' } },
  { cat: 'documents', keys: ['Ctrl', 'O'], name: { ar: 'فتح', en: 'Open' }, desc: { ar: 'فتح مستند محفوظ مسبقًا', en: 'Open an existing saved document' } },
  { cat: 'documents', keys: ['Ctrl', 'S'], name: { ar: 'حفظ', en: 'Save' }, desc: { ar: 'حفظ المستند الحالي', en: 'Save the current document' } },
  { cat: 'documents', keys: ['F12'], name: { ar: 'حفظ باسم', en: 'Save As' }, desc: { ar: 'حفظ نسخة جديدة من المستند باسم مختلف', en: 'Save a new copy of the document with a different name' } },
  { cat: 'documents', keys: ['Ctrl', 'P'], name: { ar: 'طباعة', en: 'Print' }, desc: { ar: 'فتح خيارات الطباعة للمستند', en: 'Open the print options for the document' } },
  { cat: 'documents', keys: ['Ctrl', 'W'], name: { ar: 'إغلاق المستند', en: 'Close Document' }, desc: { ar: 'إغلاق المستند الحالي', en: 'Close the current document' } },
  { cat: 'documents', keys: ['Alt', 'F4'], name: { ar: 'إغلاق وورد', en: 'Close Word' }, desc: { ar: 'إغلاق برنامج وورد بالكامل', en: 'Close the Word application entirely' } },
  { cat: 'documents', keys: ['Ctrl', 'Alt', 'S'], name: { ar: 'تقسيم النافذة', en: 'Split Window' }, desc: { ar: 'تقسيم نافذة المستند لمعاينة جزأين منه', en: 'Split the document window to view two parts at once' } },

  /* ---------------- NAVIGATION ---------------- */
  { cat: 'navigation', keys: ['Ctrl', 'Home'], name: { ar: 'بداية المستند', en: 'Go to Start' }, desc: { ar: 'الانتقال إلى بداية المستند مباشرة', en: 'Jump straight to the beginning of the document' } },
  { cat: 'navigation', keys: ['Ctrl', 'End'], name: { ar: 'نهاية المستند', en: 'Go to End' }, desc: { ar: 'الانتقال إلى نهاية المستند مباشرة', en: 'Jump straight to the end of the document' } },
  { cat: 'navigation', keys: ['Home'], name: { ar: 'بداية السطر', en: 'Line Start' }, desc: { ar: 'الانتقال إلى بداية السطر الحالي', en: 'Move to the start of the current line' } },
  { cat: 'navigation', keys: ['End'], name: { ar: 'نهاية السطر', en: 'Line End' }, desc: { ar: 'الانتقال إلى نهاية السطر الحالي', en: 'Move to the end of the current line' } },
  { cat: 'navigation', keys: ['Ctrl', 'PageDown'], name: { ar: 'الصفحة التالية', en: 'Next Page' }, desc: { ar: 'الانتقال إلى الصفحة التالية', en: 'Move to the next page' } },
  { cat: 'navigation', keys: ['Ctrl', 'PageUp'], name: { ar: 'الصفحة السابقة', en: 'Previous Page' }, desc: { ar: 'الانتقال إلى الصفحة السابقة', en: 'Move to the previous page' } },
  { cat: 'navigation', keys: ['Ctrl', '→'], name: { ar: 'الكلمة التالية', en: 'Next Word' }, desc: { ar: 'نقل المؤشر إلى بداية الكلمة التالية', en: 'Move the cursor to the start of the next word' } },
  { cat: 'navigation', keys: ['Ctrl', '←'], name: { ar: 'الكلمة السابقة', en: 'Previous Word' }, desc: { ar: 'نقل المؤشر إلى بداية الكلمة السابقة', en: 'Move the cursor to the start of the previous word' } },
  { cat: 'navigation', keys: ['Ctrl', '↑'], name: { ar: 'الفقرة السابقة', en: 'Previous Paragraph' }, desc: { ar: 'نقل المؤشر لبداية الفقرة السابقة', en: 'Move the cursor to the start of the previous paragraph' } },
  { cat: 'navigation', keys: ['Ctrl', '↓'], name: { ar: 'الفقرة التالية', en: 'Next Paragraph' }, desc: { ar: 'نقل المؤشر لبداية الفقرة التالية', en: 'Move the cursor to the start of the next paragraph' } },
  { cat: 'navigation', keys: ['Page Up'], name: { ar: 'تمرير شاشة للأعلى', en: 'Scroll Up One Screen' }, desc: { ar: 'التمرير لأعلى بمقدار شاشة كاملة', en: 'Scroll up by one full screen' } },
  { cat: 'navigation', keys: ['Page Down'], name: { ar: 'تمرير شاشة للأسفل', en: 'Scroll Down One Screen' }, desc: { ar: 'التمرير لأسفل بمقدار شاشة كاملة', en: 'Scroll down by one full screen' } },
  { cat: 'navigation', keys: ['Ctrl', 'Alt', 'Home'], name: { ar: 'أداة التصفح', en: 'Browse Object' }, desc: { ar: 'اختيار وحدة التصفح (صفحة، عنوان، جدول...)', en: 'Choose what to browse by (page, heading, table...)' } },
  { cat: 'navigation', keys: ['Shift', 'F5'], name: { ar: 'آخر موضع تعديل', en: 'Last Edit Location' }, desc: { ar: 'الانتقال بين آخر مواضع التعديل التي زرتها', en: 'Cycle through your most recent edit locations' } },

  /* ---------------- TABLES ---------------- */
  { cat: 'tables', keys: ['Tab'], name: { ar: 'الخلية التالية', en: 'Next Cell' }, desc: { ar: 'الانتقال إلى الخلية التالية في الجدول', en: 'Move to the next cell in a table' } },
  { cat: 'tables', keys: ['Shift', 'Tab'], name: { ar: 'الخلية السابقة', en: 'Previous Cell' }, desc: { ar: 'الانتقال إلى الخلية السابقة في الجدول', en: 'Move to the previous cell in a table' } },
  { cat: 'tables', keys: ['Tab'], name: { ar: 'إضافة صف جديد', en: 'Add New Row' }, desc: { ar: 'إضافة صف جديد عند الضغط في آخر خلية', en: 'Press Tab in the last cell to add a new row' } },
  { cat: 'tables', keys: ['Alt', 'Home'], name: { ar: 'أول خلية بالصف', en: 'First Cell in Row' }, desc: { ar: 'الانتقال إلى أول خلية في الصف الحالي', en: 'Move to the first cell in the current row' } },
  { cat: 'tables', keys: ['Alt', 'End'], name: { ar: 'آخر خلية بالصف', en: 'Last Cell in Row' }, desc: { ar: 'الانتقال إلى آخر خلية في الصف الحالي', en: 'Move to the last cell in the current row' } },
  { cat: 'tables', keys: ['Alt', 'PageUp'], name: { ar: 'أول خلية بالعمود', en: 'First Cell in Column' }, desc: { ar: 'الانتقال إلى أول خلية في العمود الحالي', en: 'Move to the first cell in the current column' } },
  { cat: 'tables', keys: ['Alt', 'PageDown'], name: { ar: 'آخر خلية بالعمود', en: 'Last Cell in Column' }, desc: { ar: 'الانتقال إلى آخر خلية في العمود الحالي', en: 'Move to the last cell in the current column' } },
  { cat: 'tables', keys: ['Ctrl', 'Tab'], name: { ar: 'إدراج جدولة داخل الخلية', en: 'Insert Tab in Cell' }, desc: { ar: 'إدراج علامة جدولة داخل الخلية بدل الانتقال منها', en: 'Insert an actual tab character inside a cell' } },

  /* ---------------- OBJECTS ---------------- */
  { cat: 'objects', keys: ['Ctrl', 'K'], name: { ar: 'إدراج رابط', en: 'Insert Hyperlink' }, desc: { ar: 'إدراج رابط تشعبي للنص المحدد', en: 'Insert a hyperlink for the selected text' } },
  { cat: 'objects', keys: ['Ctrl', 'Enter'], name: { ar: 'فاصل صفحة', en: 'Page Break' }, desc: { ar: 'إدراج فاصل صفحة عند موضع المؤشر', en: 'Insert a page break at the cursor position' } },
  { cat: 'objects', keys: ['Ctrl', 'Shift', 'Enter'], name: { ar: 'فاصل عمود', en: 'Column Break' }, desc: { ar: 'إدراج فاصل عمود عند موضع المؤشر', en: 'Insert a column break at the cursor position' } },
  { cat: 'objects', keys: ['Shift', 'Enter'], name: { ar: 'فاصل سطر', en: 'Line Break' }, desc: { ar: 'إدراج سطر جديد دون بدء فقرة جديدة', en: 'Insert a new line without starting a new paragraph' } },
  { cat: 'objects', keys: ['Alt', 'Shift', 'D'], name: { ar: 'إدراج التاريخ', en: 'Insert Date' }, desc: { ar: 'إدراج تاريخ اليوم تلقائيًا في المستند', en: "Insert today's date automatically" } },
  { cat: 'objects', keys: ['Alt', 'Shift', 'T'], name: { ar: 'إدراج الوقت', en: 'Insert Time' }, desc: { ar: 'إدراج الوقت الحالي تلقائيًا في المستند', en: 'Insert the current time automatically' } },
  { cat: 'objects', keys: ['Ctrl', 'F9'], name: { ar: 'إدراج حقل', en: 'Insert Field' }, desc: { ar: 'إدراج أقواس حقل فارغة', en: 'Insert empty field braces' } },
  { cat: 'objects', keys: ['F9'], name: { ar: 'تحديث الحقل', en: 'Update Field' }, desc: { ar: 'تحديث قيمة الحقل المحدد', en: 'Update the value of the selected field' } },
  { cat: 'objects', keys: ['Ctrl', 'Shift', 'F9'], name: { ar: 'فصل ارتباط الحقل', en: 'Unlink Field' }, desc: { ar: 'تحويل الحقل إلى نص عادي ثابت', en: 'Convert a field into permanent plain text' } },
  { cat: 'objects', keys: ['Ctrl', 'Alt', 'F'], name: { ar: 'إدراج حاشية سفلية', en: 'Insert Footnote' }, desc: { ar: 'إدراج حاشية سفلية عند موضع المؤشر', en: 'Insert a footnote at the cursor position' } },
  { cat: 'objects', keys: ['Ctrl', 'Alt', 'D'], name: { ar: 'إدراج حاشية ختامية', en: 'Insert Endnote' }, desc: { ar: 'إدراج حاشية ختامية عند موضع المؤشر', en: 'Insert an endnote at the cursor position' } },
  { cat: 'objects', keys: ['Ctrl', 'Shift', 'Space'], name: { ar: 'مسافة غير قابلة للفصل', en: 'Non-breaking Space' }, desc: { ar: 'إدراج مسافة تمنع فصل كلمتين عبر سطرين', en: 'Insert a space that keeps two words on the same line' } },
  { cat: 'objects', keys: ['Ctrl', 'Shift', '-'], name: { ar: 'شرطة غير قابلة للفصل', en: 'Non-breaking Hyphen' }, desc: { ar: 'إدراج شرطة تمنع فصل الكلمة عبر سطرين', en: 'Insert a hyphen that keeps a word on the same line' } },

  /* ---------------- VIEW & ACCESS ---------------- */
  { cat: 'view', keys: ['Ctrl', 'Alt', 'P'], name: { ar: 'عرض تخطيط الطباعة', en: 'Print Layout View' }, desc: { ar: 'التبديل إلى عرض تخطيط الطباعة', en: 'Switch to Print Layout view' } },
  { cat: 'view', keys: ['Ctrl', 'Alt', 'O'], name: { ar: 'عرض المخطط التفصيلي', en: 'Outline View' }, desc: { ar: 'التبديل إلى عرض المخطط التفصيلي', en: 'Switch to Outline view' } },
  { cat: 'view', keys: ['Ctrl', 'Alt', 'N'], name: { ar: 'العرض العادي', en: 'Draft / Normal View' }, desc: { ar: 'التبديل إلى العرض العادي (المسودة)', en: 'Switch to Draft (Normal) view' } },
  { cat: 'view', keys: ['Ctrl', 'Shift', '8'], name: { ar: 'إظهار علامات التنسيق', en: 'Show Formatting Marks' }, desc: { ar: 'إظهار أو إخفاء علامات الفقرة والمسافات', en: 'Show or hide paragraph and space marks' } },
  { cat: 'view', keys: ['Ctrl', 'F1'], name: { ar: 'طي/فتح الشريط', en: 'Toggle Ribbon' }, desc: { ar: 'طي أو فتح شريط الأدوات (Ribbon)', en: 'Collapse or expand the Ribbon' } },
  { cat: 'view', keys: ['Alt', 'F10'], name: { ar: 'جزء التحديد', en: 'Selection Pane' }, desc: { ar: 'فتح جزء تحديد الكائنات والعناصر', en: 'Open the Selection Pane for objects' } },
  { cat: 'view', keys: ['Ctrl', 'Shift', 'F'], name: { ar: 'مربع اسم الخط', en: 'Font Name Box' }, desc: { ar: 'نقل التركيز إلى مربع اسم الخط', en: 'Move focus to the Font Name box' } },
  { cat: 'view', keys: ['Ctrl', 'Shift', 'P'], name: { ar: 'مربع حجم الخط', en: 'Font Size Box' }, desc: { ar: 'نقل التركيز إلى مربع حجم الخط', en: 'Move focus to the Font Size box' } },

  /* ---------------- REVIEW & PROOFING ---------------- */
  { cat: 'review', keys: ['F7'], name: { ar: 'التدقيق الإملائي', en: 'Spelling & Grammar' }, desc: { ar: 'بدء فحص الإملاء والقواعد في المستند', en: 'Start checking spelling and grammar' } },
  { cat: 'review', keys: ['Shift', 'F7'], name: { ar: 'قاموس المرادفات', en: 'Thesaurus' }, desc: { ar: 'فتح قاموس المرادفات للكلمة المحددة', en: 'Open the thesaurus for the selected word' } },
  { cat: 'review', keys: ['Ctrl', 'Shift', 'E'], name: { ar: 'تتبع التغييرات', en: 'Track Changes' }, desc: { ar: 'تفعيل أو إيقاف تتبع التغييرات', en: 'Turn Track Changes on or off' } },
  { cat: 'review', keys: ['Ctrl', 'Alt', 'M'], name: { ar: 'إدراج تعليق', en: 'Insert Comment' }, desc: { ar: 'إضافة تعليق مرتبط بالنص المحدد', en: 'Add a comment attached to the selection' } },
];
